// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: WebhookSubscriptionRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockWebhookSubscriptionRepository is a mock of WebhookSubscriptionRepository interface.
type MockWebhookSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookSubscriptionRepositoryMockRecorder
}

// MockWebhookSubscriptionRepositoryMockRecorder is the mock recorder for MockWebhookSubscriptionRepository.
type MockWebhookSubscriptionRepositoryMockRecorder struct {
	mock *MockWebhookSubscriptionRepository
}

// NewMockWebhookSubscriptionRepository creates a new mock instance.
func NewMockWebhookSubscriptionRepository(ctrl *gomock.Controller) *MockWebhookSubscriptionRepository {
	mock := &MockWebhookSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockWebhookSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookSubscriptionRepository) EXPECT() *MockWebhookSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWebhookSubscriptionRepository) Create(arg0 context.Context, arg1 string, arg2 *domain.WebhookSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWebhookSubscriptionRepositoryMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWebhookSubscriptionRepository)(nil).Create), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockWebhookSubscriptionRepository) Delete(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWebhookSubscriptionRepositoryMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWebhookSubscriptionRepository)(nil).Delete), arg0, arg1, arg2)
}

// DisableWithReason mocks base method.
func (m *MockWebhookSubscriptionRepository) DisableWithReason(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableWithReason", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableWithReason indicates an expected call of DisableWithReason.
func (mr *MockWebhookSubscriptionRepositoryMockRecorder) DisableWithReason(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableWithReason", reflect.TypeOf((*MockWebhookSubscriptionRepository)(nil).DisableWithReason), arg0, arg1, arg2, arg3)
}

// GetByID mocks base method.
func (m *MockWebhookSubscriptionRepository) GetByID(arg0 context.Context, arg1, arg2 string) (*domain.WebhookSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.WebhookSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockWebhookSubscriptionRepositoryMockRecorder) GetByID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockWebhookSubscriptionRepository)(nil).GetByID), arg0, arg1, arg2)
}

// IncrementFailures mocks base method.
func (m *MockWebhookSubscriptionRepository) IncrementFailures(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementFailures", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementFailures indicates an expected call of IncrementFailures.
func (mr *MockWebhookSubscriptionRepositoryMockRecorder) IncrementFailures(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementFailures", reflect.TypeOf((*MockWebhookSubscriptionRepository)(nil).IncrementFailures), arg0, arg1, arg2)
}

// List mocks base method.
func (m *MockWebhookSubscriptionRepository) List(arg0 context.Context, arg1 string) ([]*domain.WebhookSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*domain.WebhookSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockWebhookSubscriptionRepositoryMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockWebhookSubscriptionRepository)(nil).List), arg0, arg1)
}

// ResetFailures mocks base method.
func (m *MockWebhookSubscriptionRepository) ResetFailures(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetFailures", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetFailures indicates an expected call of ResetFailures.
func (mr *MockWebhookSubscriptionRepositoryMockRecorder) ResetFailures(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetFailures", reflect.TypeOf((*MockWebhookSubscriptionRepository)(nil).ResetFailures), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockWebhookSubscriptionRepository) Update(arg0 context.Context, arg1 string, arg2 *domain.WebhookSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWebhookSubscriptionRepositoryMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWebhookSubscriptionRepository)(nil).Update), arg0, arg1, arg2)
}

// UpdateLastDeliveryAt mocks base method.
func (m *MockWebhookSubscriptionRepository) UpdateLastDeliveryAt(arg0 context.Context, arg1, arg2 string, arg3 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastDeliveryAt", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastDeliveryAt indicates an expected call of UpdateLastDeliveryAt.
func (mr *MockWebhookSubscriptionRepositoryMockRecorder) UpdateLastDeliveryAt(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastDeliveryAt", reflect.TypeOf((*MockWebhookSubscriptionRepository)(nil).UpdateLastDeliveryAt), arg0, arg1, arg2, arg3)
}
