// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: TaskRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockTaskRepository is a mock of TaskRepository interface.
type MockTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepositoryMockRecorder
}

// MockTaskRepositoryMockRecorder is the mock recorder for MockTaskRepository.
type MockTaskRepositoryMockRecorder struct {
	mock *MockTaskRepository
}

// NewMockTaskRepository creates a new mock instance.
func NewMockTaskRepository(ctrl *gomock.Controller) *MockTaskRepository {
	mock := &MockTaskRepository{ctrl: ctrl}
	mock.recorder = &MockTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepository) EXPECT() *MockTaskRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTaskRepository) Create(arg0 context.Context, arg1 string, arg2 *domain.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTaskRepositoryMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaskRepository)(nil).Create), arg0, arg1, arg2)
}

// CreateTx mocks base method.
func (m *MockTaskRepository) CreateTx(arg0 context.Context, arg1 *sql.Tx, arg2 string, arg3 *domain.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTx indicates an expected call of CreateTx.
func (mr *MockTaskRepositoryMockRecorder) CreateTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTx", reflect.TypeOf((*MockTaskRepository)(nil).CreateTx), arg0, arg1, arg2, arg3)
}

// Delete mocks base method.
func (m *MockTaskRepository) Delete(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaskRepositoryMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTaskRepository)(nil).Delete), arg0, arg1, arg2)
}

// DeleteAll mocks base method.
func (m *MockTaskRepository) DeleteAll(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockTaskRepositoryMockRecorder) DeleteAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockTaskRepository)(nil).DeleteAll), arg0, arg1)
}

// Get mocks base method.
func (m *MockTaskRepository) Get(arg0 context.Context, arg1, arg2 string) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTaskRepositoryMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTaskRepository)(nil).Get), arg0, arg1, arg2)
}

// GetNextBatch mocks base method.
func (m *MockTaskRepository) GetNextBatch(arg0 context.Context, arg1 int) ([]*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextBatch", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextBatch indicates an expected call of GetNextBatch.
func (mr *MockTaskRepositoryMockRecorder) GetNextBatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextBatch", reflect.TypeOf((*MockTaskRepository)(nil).GetNextBatch), arg0, arg1)
}

// GetTaskByBroadcastID mocks base method.
func (m *MockTaskRepository) GetTaskByBroadcastID(arg0 context.Context, arg1, arg2 string) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByBroadcastID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByBroadcastID indicates an expected call of GetTaskByBroadcastID.
func (mr *MockTaskRepositoryMockRecorder) GetTaskByBroadcastID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByBroadcastID", reflect.TypeOf((*MockTaskRepository)(nil).GetTaskByBroadcastID), arg0, arg1, arg2)
}

// GetTaskByBroadcastIDTx mocks base method.
func (m *MockTaskRepository) GetTaskByBroadcastIDTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByBroadcastIDTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByBroadcastIDTx indicates an expected call of GetTaskByBroadcastIDTx.
func (mr *MockTaskRepositoryMockRecorder) GetTaskByBroadcastIDTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByBroadcastIDTx", reflect.TypeOf((*MockTaskRepository)(nil).GetTaskByBroadcastIDTx), arg0, arg1, arg2, arg3)
}

// GetTaskByIntegrationID mocks base method.
func (m *MockTaskRepository) GetTaskByIntegrationID(arg0 context.Context, arg1, arg2 string) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByIntegrationID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByIntegrationID indicates an expected call of GetTaskByIntegrationID.
func (mr *MockTaskRepositoryMockRecorder) GetTaskByIntegrationID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByIntegrationID", reflect.TypeOf((*MockTaskRepository)(nil).GetTaskByIntegrationID), arg0, arg1, arg2)
}

// GetTaskByIntegrationIDTx mocks base method.
func (m *MockTaskRepository) GetTaskByIntegrationIDTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByIntegrationIDTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByIntegrationIDTx indicates an expected call of GetTaskByIntegrationIDTx.
func (mr *MockTaskRepositoryMockRecorder) GetTaskByIntegrationIDTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByIntegrationIDTx", reflect.TypeOf((*MockTaskRepository)(nil).GetTaskByIntegrationIDTx), arg0, arg1, arg2, arg3)
}

// GetTx mocks base method.
func (m *MockTaskRepository) GetTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTx indicates an expected call of GetTx.
func (mr *MockTaskRepositoryMockRecorder) GetTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTx", reflect.TypeOf((*MockTaskRepository)(nil).GetTx), arg0, arg1, arg2, arg3)
}

// List mocks base method.
func (m *MockTaskRepository) List(arg0 context.Context, arg1 string, arg2 domain.TaskFilter) ([]*domain.Task, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.Task)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTaskRepositoryMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaskRepository)(nil).List), arg0, arg1, arg2)
}

// MarkAsCompleted mocks base method.
func (m *MockTaskRepository) MarkAsCompleted(arg0 context.Context, arg1, arg2 string, arg3 *domain.TaskState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsCompleted", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsCompleted indicates an expected call of MarkAsCompleted.
func (mr *MockTaskRepositoryMockRecorder) MarkAsCompleted(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsCompleted", reflect.TypeOf((*MockTaskRepository)(nil).MarkAsCompleted), arg0, arg1, arg2, arg3)
}

// MarkAsCompletedTx mocks base method.
func (m *MockTaskRepository) MarkAsCompletedTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string, arg4 *domain.TaskState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsCompletedTx", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsCompletedTx indicates an expected call of MarkAsCompletedTx.
func (mr *MockTaskRepositoryMockRecorder) MarkAsCompletedTx(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsCompletedTx", reflect.TypeOf((*MockTaskRepository)(nil).MarkAsCompletedTx), arg0, arg1, arg2, arg3, arg4)
}

// MarkAsFailed mocks base method.
func (m *MockTaskRepository) MarkAsFailed(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsFailed", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsFailed indicates an expected call of MarkAsFailed.
func (mr *MockTaskRepositoryMockRecorder) MarkAsFailed(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsFailed", reflect.TypeOf((*MockTaskRepository)(nil).MarkAsFailed), arg0, arg1, arg2, arg3)
}

// MarkAsFailedTx mocks base method.
func (m *MockTaskRepository) MarkAsFailedTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsFailedTx", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsFailedTx indicates an expected call of MarkAsFailedTx.
func (mr *MockTaskRepositoryMockRecorder) MarkAsFailedTx(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsFailedTx", reflect.TypeOf((*MockTaskRepository)(nil).MarkAsFailedTx), arg0, arg1, arg2, arg3, arg4)
}

// MarkAsPaused mocks base method.
func (m *MockTaskRepository) MarkAsPaused(arg0 context.Context, arg1, arg2 string, arg3 time.Time, arg4 float64, arg5 *domain.TaskState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsPaused", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsPaused indicates an expected call of MarkAsPaused.
func (mr *MockTaskRepositoryMockRecorder) MarkAsPaused(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsPaused", reflect.TypeOf((*MockTaskRepository)(nil).MarkAsPaused), arg0, arg1, arg2, arg3, arg4, arg5)
}

// MarkAsPausedTx mocks base method.
func (m *MockTaskRepository) MarkAsPausedTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string, arg4 time.Time, arg5 float64, arg6 *domain.TaskState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsPausedTx", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsPausedTx indicates an expected call of MarkAsPausedTx.
func (mr *MockTaskRepositoryMockRecorder) MarkAsPausedTx(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsPausedTx", reflect.TypeOf((*MockTaskRepository)(nil).MarkAsPausedTx), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// MarkAsPending mocks base method.
func (m *MockTaskRepository) MarkAsPending(arg0 context.Context, arg1, arg2 string, arg3 time.Time, arg4 float64, arg5 *domain.TaskState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsPending", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsPending indicates an expected call of MarkAsPending.
func (mr *MockTaskRepositoryMockRecorder) MarkAsPending(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsPending", reflect.TypeOf((*MockTaskRepository)(nil).MarkAsPending), arg0, arg1, arg2, arg3, arg4, arg5)
}

// MarkAsPendingTx mocks base method.
func (m *MockTaskRepository) MarkAsPendingTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string, arg4 time.Time, arg5 float64, arg6 *domain.TaskState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsPendingTx", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsPendingTx indicates an expected call of MarkAsPendingTx.
func (mr *MockTaskRepositoryMockRecorder) MarkAsPendingTx(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsPendingTx", reflect.TypeOf((*MockTaskRepository)(nil).MarkAsPendingTx), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// MarkAsRunning mocks base method.
func (m *MockTaskRepository) MarkAsRunning(arg0 context.Context, arg1, arg2 string, arg3 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRunning", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRunning indicates an expected call of MarkAsRunning.
func (mr *MockTaskRepositoryMockRecorder) MarkAsRunning(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRunning", reflect.TypeOf((*MockTaskRepository)(nil).MarkAsRunning), arg0, arg1, arg2, arg3)
}

// MarkAsRunningTx mocks base method.
func (m *MockTaskRepository) MarkAsRunningTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string, arg4 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRunningTx", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRunningTx indicates an expected call of MarkAsRunningTx.
func (mr *MockTaskRepositoryMockRecorder) MarkAsRunningTx(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRunningTx", reflect.TypeOf((*MockTaskRepository)(nil).MarkAsRunningTx), arg0, arg1, arg2, arg3, arg4)
}

// ReleaseTask mocks base method.
func (m *MockTaskRepository) ReleaseTask(arg0 context.Context, arg1, arg2, arg3 string, arg4 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseTask", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseTask indicates an expected call of ReleaseTask.
func (mr *MockTaskRepositoryMockRecorder) ReleaseTask(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseTask", reflect.TypeOf((*MockTaskRepository)(nil).ReleaseTask), arg0, arg1, arg2, arg3, arg4)
}

// ReleaseTaskTx mocks base method.
func (m *MockTaskRepository) ReleaseTaskTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3, arg4 string, arg5 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseTaskTx", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseTaskTx indicates an expected call of ReleaseTaskTx.
func (mr *MockTaskRepositoryMockRecorder) ReleaseTaskTx(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseTaskTx", reflect.TypeOf((*MockTaskRepository)(nil).ReleaseTaskTx), arg0, arg1, arg2, arg3, arg4, arg5)
}

// SaveState mocks base method.
func (m *MockTaskRepository) SaveState(arg0 context.Context, arg1, arg2 string, arg3 float64, arg4 *domain.TaskState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveState", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveState indicates an expected call of SaveState.
func (mr *MockTaskRepositoryMockRecorder) SaveState(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveState", reflect.TypeOf((*MockTaskRepository)(nil).SaveState), arg0, arg1, arg2, arg3, arg4)
}

// SaveStateTx mocks base method.
func (m *MockTaskRepository) SaveStateTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string, arg4 float64, arg5 *domain.TaskState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveStateTx", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveStateTx indicates an expected call of SaveStateTx.
func (mr *MockTaskRepositoryMockRecorder) SaveStateTx(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveStateTx", reflect.TypeOf((*MockTaskRepository)(nil).SaveStateTx), arg0, arg1, arg2, arg3, arg4, arg5)
}

// Update mocks base method.
func (m *MockTaskRepository) Update(arg0 context.Context, arg1 string, arg2 *domain.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTaskRepositoryMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaskRepository)(nil).Update), arg0, arg1, arg2)
}

// UpdateTx mocks base method.
func (m *MockTaskRepository) UpdateTx(arg0 context.Context, arg1 *sql.Tx, arg2 string, arg3 *domain.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTx indicates an expected call of UpdateTx.
func (mr *MockTaskRepositoryMockRecorder) UpdateTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTx", reflect.TypeOf((*MockTaskRepository)(nil).UpdateTx), arg0, arg1, arg2, arg3)
}

// WithTransaction mocks base method.
func (m *MockTaskRepository) WithTransaction(arg0 context.Context, arg1 func(*sql.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockTaskRepositoryMockRecorder) WithTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockTaskRepository)(nil).WithTransaction), arg0, arg1)
}
