// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: InboundWebhookEventRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockInboundWebhookEventRepository is a mock of InboundWebhookEventRepository interface.
type MockInboundWebhookEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInboundWebhookEventRepositoryMockRecorder
}

// MockInboundWebhookEventRepositoryMockRecorder is the mock recorder for MockInboundWebhookEventRepository.
type MockInboundWebhookEventRepositoryMockRecorder struct {
	mock *MockInboundWebhookEventRepository
}

// NewMockInboundWebhookEventRepository creates a new mock instance.
func NewMockInboundWebhookEventRepository(ctrl *gomock.Controller) *MockInboundWebhookEventRepository {
	mock := &MockInboundWebhookEventRepository{ctrl: ctrl}
	mock.recorder = &MockInboundWebhookEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInboundWebhookEventRepository) EXPECT() *MockInboundWebhookEventRepositoryMockRecorder {
	return m.recorder
}

// CountConsecutiveSoftBounces mocks base method.
func (m *MockInboundWebhookEventRepository) CountConsecutiveSoftBounces(arg0 context.Context, arg1 string, arg2 []string) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountConsecutiveSoftBounces", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountConsecutiveSoftBounces indicates an expected call of CountConsecutiveSoftBounces.
func (mr *MockInboundWebhookEventRepositoryMockRecorder) CountConsecutiveSoftBounces(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountConsecutiveSoftBounces", reflect.TypeOf((*MockInboundWebhookEventRepository)(nil).CountConsecutiveSoftBounces), arg0, arg1, arg2)
}

// DeleteForEmail mocks base method.
func (m *MockInboundWebhookEventRepository) DeleteForEmail(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteForEmail", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteForEmail indicates an expected call of DeleteForEmail.
func (mr *MockInboundWebhookEventRepositoryMockRecorder) DeleteForEmail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteForEmail", reflect.TypeOf((*MockInboundWebhookEventRepository)(nil).DeleteForEmail), arg0, arg1, arg2)
}

// ListEvents mocks base method.
func (m *MockInboundWebhookEventRepository) ListEvents(arg0 context.Context, arg1 string, arg2 domain.InboundWebhookEventListParams) (*domain.InboundWebhookEventListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.InboundWebhookEventListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockInboundWebhookEventRepositoryMockRecorder) ListEvents(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockInboundWebhookEventRepository)(nil).ListEvents), arg0, arg1, arg2)
}

// StoreEvents mocks base method.
func (m *MockInboundWebhookEventRepository) StoreEvents(arg0 context.Context, arg1 string, arg2 []*domain.InboundWebhookEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreEvents", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreEvents indicates an expected call of StoreEvents.
func (mr *MockInboundWebhookEventRepositoryMockRecorder) StoreEvents(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreEvents", reflect.TypeOf((*MockInboundWebhookEventRepository)(nil).StoreEvents), arg0, arg1, arg2)
}

// StoreReplyEvent mocks base method.
func (m *MockInboundWebhookEventRepository) StoreReplyEvent(arg0 context.Context, arg1 string, arg2 *domain.InboundWebhookEvent) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreReplyEvent", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreReplyEvent indicates an expected call of StoreReplyEvent.
func (mr *MockInboundWebhookEventRepositoryMockRecorder) StoreReplyEvent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreReplyEvent", reflect.TypeOf((*MockInboundWebhookEventRepository)(nil).StoreReplyEvent), arg0, arg1, arg2)
}
