// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: FederatedIdentityRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockFederatedIdentityRepository is a mock of FederatedIdentityRepository interface.
type MockFederatedIdentityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFederatedIdentityRepositoryMockRecorder
}

// MockFederatedIdentityRepositoryMockRecorder is the mock recorder for MockFederatedIdentityRepository.
type MockFederatedIdentityRepositoryMockRecorder struct {
	mock *MockFederatedIdentityRepository
}

// NewMockFederatedIdentityRepository creates a new mock instance.
func NewMockFederatedIdentityRepository(ctrl *gomock.Controller) *MockFederatedIdentityRepository {
	mock := &MockFederatedIdentityRepository{ctrl: ctrl}
	mock.recorder = &MockFederatedIdentityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFederatedIdentityRepository) EXPECT() *MockFederatedIdentityRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFederatedIdentityRepository) Create(arg0 context.Context, arg1 *domain.FederatedIdentity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFederatedIdentityRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFederatedIdentityRepository)(nil).Create), arg0, arg1)
}

// GetByIssuerSubject mocks base method.
func (m *MockFederatedIdentityRepository) GetByIssuerSubject(arg0 context.Context, arg1, arg2 string) (*domain.FederatedIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIssuerSubject", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.FederatedIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIssuerSubject indicates an expected call of GetByIssuerSubject.
func (mr *MockFederatedIdentityRepositoryMockRecorder) GetByIssuerSubject(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIssuerSubject", reflect.TypeOf((*MockFederatedIdentityRepository)(nil).GetByIssuerSubject), arg0, arg1, arg2)
}

// GetByUserAndIssuer mocks base method.
func (m *MockFederatedIdentityRepository) GetByUserAndIssuer(arg0 context.Context, arg1, arg2 string) (*domain.FederatedIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserAndIssuer", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.FederatedIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserAndIssuer indicates an expected call of GetByUserAndIssuer.
func (mr *MockFederatedIdentityRepositoryMockRecorder) GetByUserAndIssuer(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserAndIssuer", reflect.TypeOf((*MockFederatedIdentityRepository)(nil).GetByUserAndIssuer), arg0, arg1, arg2)
}

// ListByUserID mocks base method.
func (m *MockFederatedIdentityRepository) ListByUserID(arg0 context.Context, arg1 string) ([]*domain.FederatedIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", arg0, arg1)
	ret0, _ := ret[0].([]*domain.FederatedIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockFederatedIdentityRepositoryMockRecorder) ListByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockFederatedIdentityRepository)(nil).ListByUserID), arg0, arg1)
}
