// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: OIDCServiceInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockOIDCServiceInterface is a mock of OIDCServiceInterface interface.
type MockOIDCServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOIDCServiceInterfaceMockRecorder
}

// MockOIDCServiceInterfaceMockRecorder is the mock recorder for MockOIDCServiceInterface.
type MockOIDCServiceInterfaceMockRecorder struct {
	mock *MockOIDCServiceInterface
}

// NewMockOIDCServiceInterface creates a new mock instance.
func NewMockOIDCServiceInterface(ctrl *gomock.Controller) *MockOIDCServiceInterface {
	mock := &MockOIDCServiceInterface{ctrl: ctrl}
	mock.recorder = &MockOIDCServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOIDCServiceInterface) EXPECT() *MockOIDCServiceInterfaceMockRecorder {
	return m.recorder
}

// BuildAuthURL mocks base method.
func (m *MockOIDCServiceInterface) BuildAuthURL(arg0 context.Context) (*domain.OIDCAuthRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildAuthURL", arg0)
	ret0, _ := ret[0].(*domain.OIDCAuthRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildAuthURL indicates an expected call of BuildAuthURL.
func (mr *MockOIDCServiceInterfaceMockRecorder) BuildAuthURL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildAuthURL", reflect.TypeOf((*MockOIDCServiceInterface)(nil).BuildAuthURL), arg0)
}

// ExchangeCode mocks base method.
func (m *MockOIDCServiceInterface) ExchangeCode(arg0 context.Context, arg1 string) (*domain.AuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCode", arg0, arg1)
	ret0, _ := ret[0].(*domain.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCode indicates an expected call of ExchangeCode.
func (mr *MockOIDCServiceInterfaceMockRecorder) ExchangeCode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCode", reflect.TypeOf((*MockOIDCServiceInterface)(nil).ExchangeCode), arg0, arg1)
}

// HandleCallback mocks base method.
func (m *MockOIDCServiceInterface) HandleCallback(arg0 context.Context, arg1 domain.OIDCCallbackInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCallback", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleCallback indicates an expected call of HandleCallback.
func (mr *MockOIDCServiceInterfaceMockRecorder) HandleCallback(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCallback", reflect.TypeOf((*MockOIDCServiceInterface)(nil).HandleCallback), arg0, arg1)
}

// IsEnabled mocks base method.
func (m *MockOIDCServiceInterface) IsEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnabled indicates an expected call of IsEnabled.
func (mr *MockOIDCServiceInterfaceMockRecorder) IsEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockOIDCServiceInterface)(nil).IsEnabled))
}

// OpenFlowState mocks base method.
func (m *MockOIDCServiceInterface) OpenFlowState(arg0 string) (domain.OIDCFlowState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFlowState", arg0)
	ret0, _ := ret[0].(domain.OIDCFlowState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFlowState indicates an expected call of OpenFlowState.
func (mr *MockOIDCServiceInterfaceMockRecorder) OpenFlowState(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFlowState", reflect.TypeOf((*MockOIDCServiceInterface)(nil).OpenFlowState), arg0)
}

// SealFlowState mocks base method.
func (m *MockOIDCServiceInterface) SealFlowState(arg0 domain.OIDCFlowState) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SealFlowState", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SealFlowState indicates an expected call of SealFlowState.
func (mr *MockOIDCServiceInterfaceMockRecorder) SealFlowState(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SealFlowState", reflect.TypeOf((*MockOIDCServiceInterface)(nil).SealFlowState), arg0)
}
