// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: SESv2Client)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sesv2 "github.com/aws/aws-sdk-go-v2/service/sesv2"
	gomock "github.com/golang/mock/gomock"
)

// MockSESv2Client is a mock of SESv2Client interface.
type MockSESv2Client struct {
	ctrl     *gomock.Controller
	recorder *MockSESv2ClientMockRecorder
}

// MockSESv2ClientMockRecorder is the mock recorder for MockSESv2Client.
type MockSESv2ClientMockRecorder struct {
	mock *MockSESv2Client
}

// NewMockSESv2Client creates a new mock instance.
func NewMockSESv2Client(ctrl *gomock.Controller) *MockSESv2Client {
	mock := &MockSESv2Client{ctrl: ctrl}
	mock.recorder = &MockSESv2ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSESv2Client) EXPECT() *MockSESv2ClientMockRecorder {
	return m.recorder
}

// CreateTenant mocks base method.
func (m *MockSESv2Client) CreateTenant(arg0 context.Context, arg1 *sesv2.CreateTenantInput, arg2 ...func(*sesv2.Options)) (*sesv2.CreateTenantOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTenant", varargs...)
	ret0, _ := ret[0].(*sesv2.CreateTenantOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenant indicates an expected call of CreateTenant.
func (mr *MockSESv2ClientMockRecorder) CreateTenant(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenant", reflect.TypeOf((*MockSESv2Client)(nil).CreateTenant), varargs...)
}

// CreateTenantResourceAssociation mocks base method.
func (m *MockSESv2Client) CreateTenantResourceAssociation(arg0 context.Context, arg1 *sesv2.CreateTenantResourceAssociationInput, arg2 ...func(*sesv2.Options)) (*sesv2.CreateTenantResourceAssociationOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTenantResourceAssociation", varargs...)
	ret0, _ := ret[0].(*sesv2.CreateTenantResourceAssociationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenantResourceAssociation indicates an expected call of CreateTenantResourceAssociation.
func (mr *MockSESv2ClientMockRecorder) CreateTenantResourceAssociation(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenantResourceAssociation", reflect.TypeOf((*MockSESv2Client)(nil).CreateTenantResourceAssociation), varargs...)
}

// DeleteTenant mocks base method.
func (m *MockSESv2Client) DeleteTenant(arg0 context.Context, arg1 *sesv2.DeleteTenantInput, arg2 ...func(*sesv2.Options)) (*sesv2.DeleteTenantOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteTenant", varargs...)
	ret0, _ := ret[0].(*sesv2.DeleteTenantOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTenant indicates an expected call of DeleteTenant.
func (mr *MockSESv2ClientMockRecorder) DeleteTenant(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTenant", reflect.TypeOf((*MockSESv2Client)(nil).DeleteTenant), varargs...)
}

// DeleteTenantResourceAssociation mocks base method.
func (m *MockSESv2Client) DeleteTenantResourceAssociation(arg0 context.Context, arg1 *sesv2.DeleteTenantResourceAssociationInput, arg2 ...func(*sesv2.Options)) (*sesv2.DeleteTenantResourceAssociationOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteTenantResourceAssociation", varargs...)
	ret0, _ := ret[0].(*sesv2.DeleteTenantResourceAssociationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTenantResourceAssociation indicates an expected call of DeleteTenantResourceAssociation.
func (mr *MockSESv2ClientMockRecorder) DeleteTenantResourceAssociation(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTenantResourceAssociation", reflect.TypeOf((*MockSESv2Client)(nil).DeleteTenantResourceAssociation), varargs...)
}

// GetTenant mocks base method.
func (m *MockSESv2Client) GetTenant(arg0 context.Context, arg1 *sesv2.GetTenantInput, arg2 ...func(*sesv2.Options)) (*sesv2.GetTenantOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTenant", varargs...)
	ret0, _ := ret[0].(*sesv2.GetTenantOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenant indicates an expected call of GetTenant.
func (mr *MockSESv2ClientMockRecorder) GetTenant(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenant", reflect.TypeOf((*MockSESv2Client)(nil).GetTenant), varargs...)
}

// ListEmailIdentities mocks base method.
func (m *MockSESv2Client) ListEmailIdentities(arg0 context.Context, arg1 *sesv2.ListEmailIdentitiesInput, arg2 ...func(*sesv2.Options)) (*sesv2.ListEmailIdentitiesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListEmailIdentities", varargs...)
	ret0, _ := ret[0].(*sesv2.ListEmailIdentitiesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmailIdentities indicates an expected call of ListEmailIdentities.
func (mr *MockSESv2ClientMockRecorder) ListEmailIdentities(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmailIdentities", reflect.TypeOf((*MockSESv2Client)(nil).ListEmailIdentities), varargs...)
}

// ListResourceTenants mocks base method.
func (m *MockSESv2Client) ListResourceTenants(arg0 context.Context, arg1 *sesv2.ListResourceTenantsInput, arg2 ...func(*sesv2.Options)) (*sesv2.ListResourceTenantsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListResourceTenants", varargs...)
	ret0, _ := ret[0].(*sesv2.ListResourceTenantsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResourceTenants indicates an expected call of ListResourceTenants.
func (mr *MockSESv2ClientMockRecorder) ListResourceTenants(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResourceTenants", reflect.TypeOf((*MockSESv2Client)(nil).ListResourceTenants), varargs...)
}

// ListTenantResources mocks base method.
func (m *MockSESv2Client) ListTenantResources(arg0 context.Context, arg1 *sesv2.ListTenantResourcesInput, arg2 ...func(*sesv2.Options)) (*sesv2.ListTenantResourcesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTenantResources", varargs...)
	ret0, _ := ret[0].(*sesv2.ListTenantResourcesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTenantResources indicates an expected call of ListTenantResources.
func (mr *MockSESv2ClientMockRecorder) ListTenantResources(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTenantResources", reflect.TypeOf((*MockSESv2Client)(nil).ListTenantResources), varargs...)
}

// ListTenants mocks base method.
func (m *MockSESv2Client) ListTenants(arg0 context.Context, arg1 *sesv2.ListTenantsInput, arg2 ...func(*sesv2.Options)) (*sesv2.ListTenantsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTenants", varargs...)
	ret0, _ := ret[0].(*sesv2.ListTenantsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTenants indicates an expected call of ListTenants.
func (mr *MockSESv2ClientMockRecorder) ListTenants(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTenants", reflect.TypeOf((*MockSESv2Client)(nil).ListTenants), varargs...)
}

// PutTenantSuppressionAttributes mocks base method.
func (m *MockSESv2Client) PutTenantSuppressionAttributes(arg0 context.Context, arg1 *sesv2.PutTenantSuppressionAttributesInput, arg2 ...func(*sesv2.Options)) (*sesv2.PutTenantSuppressionAttributesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutTenantSuppressionAttributes", varargs...)
	ret0, _ := ret[0].(*sesv2.PutTenantSuppressionAttributesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutTenantSuppressionAttributes indicates an expected call of PutTenantSuppressionAttributes.
func (mr *MockSESv2ClientMockRecorder) PutTenantSuppressionAttributes(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutTenantSuppressionAttributes", reflect.TypeOf((*MockSESv2Client)(nil).PutTenantSuppressionAttributes), varargs...)
}

// SendEmail mocks base method.
func (m *MockSESv2Client) SendEmail(arg0 context.Context, arg1 *sesv2.SendEmailInput, arg2 ...func(*sesv2.Options)) (*sesv2.SendEmailOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendEmail", varargs...)
	ret0, _ := ret[0].(*sesv2.SendEmailOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockSESv2ClientMockRecorder) SendEmail(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockSESv2Client)(nil).SendEmail), varargs...)
}
