// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: SESWebhookClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	request "github.com/aws/aws-sdk-go/aws/request"
	ses "github.com/aws/aws-sdk-go/service/ses"
	gomock "github.com/golang/mock/gomock"
)

// MockSESWebhookClient is a mock of SESWebhookClient interface.
type MockSESWebhookClient struct {
	ctrl     *gomock.Controller
	recorder *MockSESWebhookClientMockRecorder
}

// MockSESWebhookClientMockRecorder is the mock recorder for MockSESWebhookClient.
type MockSESWebhookClientMockRecorder struct {
	mock *MockSESWebhookClient
}

// NewMockSESWebhookClient creates a new mock instance.
func NewMockSESWebhookClient(ctrl *gomock.Controller) *MockSESWebhookClient {
	mock := &MockSESWebhookClient{ctrl: ctrl}
	mock.recorder = &MockSESWebhookClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSESWebhookClient) EXPECT() *MockSESWebhookClientMockRecorder {
	return m.recorder
}

// CreateConfigurationSetEventDestinationWithContext mocks base method.
func (m *MockSESWebhookClient) CreateConfigurationSetEventDestinationWithContext(arg0 context.Context, arg1 *ses.CreateConfigurationSetEventDestinationInput, arg2 ...request.Option) (*ses.CreateConfigurationSetEventDestinationOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateConfigurationSetEventDestinationWithContext", varargs...)
	ret0, _ := ret[0].(*ses.CreateConfigurationSetEventDestinationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConfigurationSetEventDestinationWithContext indicates an expected call of CreateConfigurationSetEventDestinationWithContext.
func (mr *MockSESWebhookClientMockRecorder) CreateConfigurationSetEventDestinationWithContext(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConfigurationSetEventDestinationWithContext", reflect.TypeOf((*MockSESWebhookClient)(nil).CreateConfigurationSetEventDestinationWithContext), varargs...)
}

// CreateConfigurationSetWithContext mocks base method.
func (m *MockSESWebhookClient) CreateConfigurationSetWithContext(arg0 context.Context, arg1 *ses.CreateConfigurationSetInput, arg2 ...request.Option) (*ses.CreateConfigurationSetOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateConfigurationSetWithContext", varargs...)
	ret0, _ := ret[0].(*ses.CreateConfigurationSetOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConfigurationSetWithContext indicates an expected call of CreateConfigurationSetWithContext.
func (mr *MockSESWebhookClientMockRecorder) CreateConfigurationSetWithContext(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConfigurationSetWithContext", reflect.TypeOf((*MockSESWebhookClient)(nil).CreateConfigurationSetWithContext), varargs...)
}

// CreateReceiptRuleSetWithContext mocks base method.
func (m *MockSESWebhookClient) CreateReceiptRuleSetWithContext(arg0 context.Context, arg1 *ses.CreateReceiptRuleSetInput, arg2 ...request.Option) (*ses.CreateReceiptRuleSetOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateReceiptRuleSetWithContext", varargs...)
	ret0, _ := ret[0].(*ses.CreateReceiptRuleSetOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReceiptRuleSetWithContext indicates an expected call of CreateReceiptRuleSetWithContext.
func (mr *MockSESWebhookClientMockRecorder) CreateReceiptRuleSetWithContext(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReceiptRuleSetWithContext", reflect.TypeOf((*MockSESWebhookClient)(nil).CreateReceiptRuleSetWithContext), varargs...)
}

// CreateReceiptRuleWithContext mocks base method.
func (m *MockSESWebhookClient) CreateReceiptRuleWithContext(arg0 context.Context, arg1 *ses.CreateReceiptRuleInput, arg2 ...request.Option) (*ses.CreateReceiptRuleOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateReceiptRuleWithContext", varargs...)
	ret0, _ := ret[0].(*ses.CreateReceiptRuleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReceiptRuleWithContext indicates an expected call of CreateReceiptRuleWithContext.
func (mr *MockSESWebhookClientMockRecorder) CreateReceiptRuleWithContext(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReceiptRuleWithContext", reflect.TypeOf((*MockSESWebhookClient)(nil).CreateReceiptRuleWithContext), varargs...)
}

// DeleteConfigurationSetEventDestinationWithContext mocks base method.
func (m *MockSESWebhookClient) DeleteConfigurationSetEventDestinationWithContext(arg0 context.Context, arg1 *ses.DeleteConfigurationSetEventDestinationInput, arg2 ...request.Option) (*ses.DeleteConfigurationSetEventDestinationOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteConfigurationSetEventDestinationWithContext", varargs...)
	ret0, _ := ret[0].(*ses.DeleteConfigurationSetEventDestinationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteConfigurationSetEventDestinationWithContext indicates an expected call of DeleteConfigurationSetEventDestinationWithContext.
func (mr *MockSESWebhookClientMockRecorder) DeleteConfigurationSetEventDestinationWithContext(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConfigurationSetEventDestinationWithContext", reflect.TypeOf((*MockSESWebhookClient)(nil).DeleteConfigurationSetEventDestinationWithContext), varargs...)
}

// DeleteConfigurationSetWithContext mocks base method.
func (m *MockSESWebhookClient) DeleteConfigurationSetWithContext(arg0 context.Context, arg1 *ses.DeleteConfigurationSetInput, arg2 ...request.Option) (*ses.DeleteConfigurationSetOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteConfigurationSetWithContext", varargs...)
	ret0, _ := ret[0].(*ses.DeleteConfigurationSetOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteConfigurationSetWithContext indicates an expected call of DeleteConfigurationSetWithContext.
func (mr *MockSESWebhookClientMockRecorder) DeleteConfigurationSetWithContext(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConfigurationSetWithContext", reflect.TypeOf((*MockSESWebhookClient)(nil).DeleteConfigurationSetWithContext), varargs...)
}

// DeleteReceiptRuleWithContext mocks base method.
func (m *MockSESWebhookClient) DeleteReceiptRuleWithContext(arg0 context.Context, arg1 *ses.DeleteReceiptRuleInput, arg2 ...request.Option) (*ses.DeleteReceiptRuleOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteReceiptRuleWithContext", varargs...)
	ret0, _ := ret[0].(*ses.DeleteReceiptRuleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteReceiptRuleWithContext indicates an expected call of DeleteReceiptRuleWithContext.
func (mr *MockSESWebhookClientMockRecorder) DeleteReceiptRuleWithContext(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReceiptRuleWithContext", reflect.TypeOf((*MockSESWebhookClient)(nil).DeleteReceiptRuleWithContext), varargs...)
}

// DescribeActiveReceiptRuleSetWithContext mocks base method.
func (m *MockSESWebhookClient) DescribeActiveReceiptRuleSetWithContext(arg0 context.Context, arg1 *ses.DescribeActiveReceiptRuleSetInput, arg2 ...request.Option) (*ses.DescribeActiveReceiptRuleSetOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeActiveReceiptRuleSetWithContext", varargs...)
	ret0, _ := ret[0].(*ses.DescribeActiveReceiptRuleSetOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeActiveReceiptRuleSetWithContext indicates an expected call of DescribeActiveReceiptRuleSetWithContext.
func (mr *MockSESWebhookClientMockRecorder) DescribeActiveReceiptRuleSetWithContext(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeActiveReceiptRuleSetWithContext", reflect.TypeOf((*MockSESWebhookClient)(nil).DescribeActiveReceiptRuleSetWithContext), varargs...)
}

// DescribeConfigurationSetWithContext mocks base method.
func (m *MockSESWebhookClient) DescribeConfigurationSetWithContext(arg0 context.Context, arg1 *ses.DescribeConfigurationSetInput, arg2 ...request.Option) (*ses.DescribeConfigurationSetOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeConfigurationSetWithContext", varargs...)
	ret0, _ := ret[0].(*ses.DescribeConfigurationSetOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeConfigurationSetWithContext indicates an expected call of DescribeConfigurationSetWithContext.
func (mr *MockSESWebhookClientMockRecorder) DescribeConfigurationSetWithContext(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeConfigurationSetWithContext", reflect.TypeOf((*MockSESWebhookClient)(nil).DescribeConfigurationSetWithContext), varargs...)
}

// ListConfigurationSetsWithContext mocks base method.
func (m *MockSESWebhookClient) ListConfigurationSetsWithContext(arg0 context.Context, arg1 *ses.ListConfigurationSetsInput, arg2 ...request.Option) (*ses.ListConfigurationSetsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListConfigurationSetsWithContext", varargs...)
	ret0, _ := ret[0].(*ses.ListConfigurationSetsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConfigurationSetsWithContext indicates an expected call of ListConfigurationSetsWithContext.
func (mr *MockSESWebhookClientMockRecorder) ListConfigurationSetsWithContext(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConfigurationSetsWithContext", reflect.TypeOf((*MockSESWebhookClient)(nil).ListConfigurationSetsWithContext), varargs...)
}

// ListIdentitiesWithContext mocks base method.
func (m *MockSESWebhookClient) ListIdentitiesWithContext(arg0 context.Context, arg1 *ses.ListIdentitiesInput, arg2 ...request.Option) (*ses.ListIdentitiesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListIdentitiesWithContext", varargs...)
	ret0, _ := ret[0].(*ses.ListIdentitiesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIdentitiesWithContext indicates an expected call of ListIdentitiesWithContext.
func (mr *MockSESWebhookClientMockRecorder) ListIdentitiesWithContext(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIdentitiesWithContext", reflect.TypeOf((*MockSESWebhookClient)(nil).ListIdentitiesWithContext), varargs...)
}

// SetActiveReceiptRuleSetWithContext mocks base method.
func (m *MockSESWebhookClient) SetActiveReceiptRuleSetWithContext(arg0 context.Context, arg1 *ses.SetActiveReceiptRuleSetInput, arg2 ...request.Option) (*ses.SetActiveReceiptRuleSetOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetActiveReceiptRuleSetWithContext", varargs...)
	ret0, _ := ret[0].(*ses.SetActiveReceiptRuleSetOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetActiveReceiptRuleSetWithContext indicates an expected call of SetActiveReceiptRuleSetWithContext.
func (mr *MockSESWebhookClientMockRecorder) SetActiveReceiptRuleSetWithContext(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActiveReceiptRuleSetWithContext", reflect.TypeOf((*MockSESWebhookClient)(nil).SetActiveReceiptRuleSetWithContext), varargs...)
}

// UpdateConfigurationSetEventDestinationWithContext mocks base method.
func (m *MockSESWebhookClient) UpdateConfigurationSetEventDestinationWithContext(arg0 context.Context, arg1 *ses.UpdateConfigurationSetEventDestinationInput, arg2 ...request.Option) (*ses.UpdateConfigurationSetEventDestinationOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateConfigurationSetEventDestinationWithContext", varargs...)
	ret0, _ := ret[0].(*ses.UpdateConfigurationSetEventDestinationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateConfigurationSetEventDestinationWithContext indicates an expected call of UpdateConfigurationSetEventDestinationWithContext.
func (mr *MockSESWebhookClientMockRecorder) UpdateConfigurationSetEventDestinationWithContext(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfigurationSetEventDestinationWithContext", reflect.TypeOf((*MockSESWebhookClient)(nil).UpdateConfigurationSetEventDestinationWithContext), varargs...)
}
