// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: ContactRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockContactRepository is a mock of ContactRepository interface.
type MockContactRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContactRepositoryMockRecorder
}

// MockContactRepositoryMockRecorder is the mock recorder for MockContactRepository.
type MockContactRepositoryMockRecorder struct {
	mock *MockContactRepository
}

// NewMockContactRepository creates a new mock instance.
func NewMockContactRepository(ctrl *gomock.Controller) *MockContactRepository {
	mock := &MockContactRepository{ctrl: ctrl}
	mock.recorder = &MockContactRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContactRepository) EXPECT() *MockContactRepositoryMockRecorder {
	return m.recorder
}

// BulkUpsertContacts mocks base method.
func (m *MockContactRepository) BulkUpsertContacts(arg0 context.Context, arg1 string, arg2 []*domain.Contact) ([]domain.BulkUpsertResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpsertContacts", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.BulkUpsertResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUpsertContacts indicates an expected call of BulkUpsertContacts.
func (mr *MockContactRepositoryMockRecorder) BulkUpsertContacts(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpsertContacts", reflect.TypeOf((*MockContactRepository)(nil).BulkUpsertContacts), arg0, arg1, arg2)
}

// Count mocks base method.
func (m *MockContactRepository) Count(arg0 context.Context, arg1 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockContactRepositoryMockRecorder) Count(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockContactRepository)(nil).Count), arg0, arg1)
}

// CountContactsForBroadcast mocks base method.
func (m *MockContactRepository) CountContactsForBroadcast(arg0 context.Context, arg1 string, arg2 domain.AudienceSettings) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountContactsForBroadcast", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountContactsForBroadcast indicates an expected call of CountContactsForBroadcast.
func (mr *MockContactRepositoryMockRecorder) CountContactsForBroadcast(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountContactsForBroadcast", reflect.TypeOf((*MockContactRepository)(nil).CountContactsForBroadcast), arg0, arg1, arg2)
}

// CreateContactIfAbsent mocks base method.
func (m *MockContactRepository) CreateContactIfAbsent(arg0 context.Context, arg1 string, arg2 *domain.Contact) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContactIfAbsent", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContactIfAbsent indicates an expected call of CreateContactIfAbsent.
func (mr *MockContactRepositoryMockRecorder) CreateContactIfAbsent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContactIfAbsent", reflect.TypeOf((*MockContactRepository)(nil).CreateContactIfAbsent), arg0, arg1, arg2)
}

// DeleteContact mocks base method.
func (m *MockContactRepository) DeleteContact(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContact", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContact indicates an expected call of DeleteContact.
func (mr *MockContactRepositoryMockRecorder) DeleteContact(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContact", reflect.TypeOf((*MockContactRepository)(nil).DeleteContact), arg0, arg1, arg2)
}

// GetBatchForSegment mocks base method.
func (m *MockContactRepository) GetBatchForSegment(arg0 context.Context, arg1 string, arg2 int64, arg3 int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBatchForSegment", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBatchForSegment indicates an expected call of GetBatchForSegment.
func (mr *MockContactRepositoryMockRecorder) GetBatchForSegment(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBatchForSegment", reflect.TypeOf((*MockContactRepository)(nil).GetBatchForSegment), arg0, arg1, arg2, arg3)
}

// GetContactByEmail mocks base method.
func (m *MockContactRepository) GetContactByEmail(arg0 context.Context, arg1, arg2 string) (*domain.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactByEmail", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContactByEmail indicates an expected call of GetContactByEmail.
func (mr *MockContactRepositoryMockRecorder) GetContactByEmail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactByEmail", reflect.TypeOf((*MockContactRepository)(nil).GetContactByEmail), arg0, arg1, arg2)
}

// GetContactByExternalID mocks base method.
func (m *MockContactRepository) GetContactByExternalID(arg0 context.Context, arg1, arg2 string) (*domain.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactByExternalID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContactByExternalID indicates an expected call of GetContactByExternalID.
func (mr *MockContactRepositoryMockRecorder) GetContactByExternalID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactByExternalID", reflect.TypeOf((*MockContactRepository)(nil).GetContactByExternalID), arg0, arg1, arg2)
}

// GetContacts mocks base method.
func (m *MockContactRepository) GetContacts(arg0 context.Context, arg1 *domain.GetContactsRequest) (*domain.GetContactsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContacts", arg0, arg1)
	ret0, _ := ret[0].(*domain.GetContactsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContacts indicates an expected call of GetContacts.
func (mr *MockContactRepositoryMockRecorder) GetContacts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContacts", reflect.TypeOf((*MockContactRepository)(nil).GetContacts), arg0, arg1)
}

// GetContactsForBroadcast mocks base method.
func (m *MockContactRepository) GetContactsForBroadcast(arg0 context.Context, arg1 string, arg2 domain.AudienceSettings, arg3 int, arg4 string) ([]*domain.ContactWithList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactsForBroadcast", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*domain.ContactWithList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContactsForBroadcast indicates an expected call of GetContactsForBroadcast.
func (mr *MockContactRepositoryMockRecorder) GetContactsForBroadcast(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactsForBroadcast", reflect.TypeOf((*MockContactRepository)(nil).GetContactsForBroadcast), arg0, arg1, arg2, arg3, arg4)
}

// MarkEmailsAsBounced mocks base method.
func (m *MockContactRepository) MarkEmailsAsBounced(arg0 context.Context, arg1 string, arg2 []string, arg3 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEmailsAsBounced", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEmailsAsBounced indicates an expected call of MarkEmailsAsBounced.
func (mr *MockContactRepositoryMockRecorder) MarkEmailsAsBounced(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEmailsAsBounced", reflect.TypeOf((*MockContactRepository)(nil).MarkEmailsAsBounced), arg0, arg1, arg2, arg3)
}

// UpsertContact mocks base method.
func (m *MockContactRepository) UpsertContact(arg0 context.Context, arg1 string, arg2 *domain.Contact) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertContact", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertContact indicates an expected call of UpsertContact.
func (mr *MockContactRepositoryMockRecorder) UpsertContact(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertContact", reflect.TypeOf((*MockContactRepository)(nil).UpsertContact), arg0, arg1, arg2)
}
