// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: InboundWebhookEventServiceInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockInboundWebhookEventServiceInterface is a mock of InboundWebhookEventServiceInterface interface.
type MockInboundWebhookEventServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInboundWebhookEventServiceInterfaceMockRecorder
}

// MockInboundWebhookEventServiceInterfaceMockRecorder is the mock recorder for MockInboundWebhookEventServiceInterface.
type MockInboundWebhookEventServiceInterfaceMockRecorder struct {
	mock *MockInboundWebhookEventServiceInterface
}

// NewMockInboundWebhookEventServiceInterface creates a new mock instance.
func NewMockInboundWebhookEventServiceInterface(ctrl *gomock.Controller) *MockInboundWebhookEventServiceInterface {
	mock := &MockInboundWebhookEventServiceInterface{ctrl: ctrl}
	mock.recorder = &MockInboundWebhookEventServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInboundWebhookEventServiceInterface) EXPECT() *MockInboundWebhookEventServiceInterfaceMockRecorder {
	return m.recorder
}

// ListEvents mocks base method.
func (m *MockInboundWebhookEventServiceInterface) ListEvents(arg0 context.Context, arg1 string, arg2 domain.InboundWebhookEventListParams) (*domain.InboundWebhookEventListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.InboundWebhookEventListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockInboundWebhookEventServiceInterfaceMockRecorder) ListEvents(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockInboundWebhookEventServiceInterface)(nil).ListEvents), arg0, arg1, arg2)
}

// ProcessInboundReply mocks base method.
func (m *MockInboundWebhookEventServiceInterface) ProcessInboundReply(arg0 context.Context, arg1, arg2 string, arg3 *domain.InboundRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessInboundReply", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessInboundReply indicates an expected call of ProcessInboundReply.
func (mr *MockInboundWebhookEventServiceInterfaceMockRecorder) ProcessInboundReply(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessInboundReply", reflect.TypeOf((*MockInboundWebhookEventServiceInterface)(nil).ProcessInboundReply), arg0, arg1, arg2, arg3)
}

// ProcessWebhook mocks base method.
func (m *MockInboundWebhookEventServiceInterface) ProcessWebhook(arg0 context.Context, arg1, arg2 string, arg3 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessWebhook", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessWebhook indicates an expected call of ProcessWebhook.
func (mr *MockInboundWebhookEventServiceInterfaceMockRecorder) ProcessWebhook(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessWebhook", reflect.TypeOf((*MockInboundWebhookEventServiceInterface)(nil).ProcessWebhook), arg0, arg1, arg2, arg3)
}
