// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: UsageService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockUsageService is a mock of UsageService interface.
type MockUsageService struct {
	ctrl     *gomock.Controller
	recorder *MockUsageServiceMockRecorder
}

// MockUsageServiceMockRecorder is the mock recorder for MockUsageService.
type MockUsageServiceMockRecorder struct {
	mock *MockUsageService
}

// NewMockUsageService creates a new mock instance.
func NewMockUsageService(ctrl *gomock.Controller) *MockUsageService {
	mock := &MockUsageService{ctrl: ctrl}
	mock.recorder = &MockUsageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageService) EXPECT() *MockUsageServiceMockRecorder {
	return m.recorder
}

// GetUsage mocks base method.
func (m *MockUsageService) GetUsage(arg0 context.Context, arg1 []time.Time) (*domain.UsageReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsage", arg0, arg1)
	ret0, _ := ret[0].(*domain.UsageReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsage indicates an expected call of GetUsage.
func (mr *MockUsageServiceMockRecorder) GetUsage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsage", reflect.TypeOf((*MockUsageService)(nil).GetUsage), arg0, arg1)
}
