// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: AnnotationService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockAnnotationService is a mock of AnnotationService interface.
type MockAnnotationService struct {
	ctrl     *gomock.Controller
	recorder *MockAnnotationServiceMockRecorder
}

// MockAnnotationServiceMockRecorder is the mock recorder for MockAnnotationService.
type MockAnnotationServiceMockRecorder struct {
	mock *MockAnnotationService
}

// NewMockAnnotationService creates a new mock instance.
func NewMockAnnotationService(ctrl *gomock.Controller) *MockAnnotationService {
	mock := &MockAnnotationService{ctrl: ctrl}
	mock.recorder = &MockAnnotationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnnotationService) EXPECT() *MockAnnotationServiceMockRecorder {
	return m.recorder
}

// CreateAnnotation mocks base method.
func (m *MockAnnotationService) CreateAnnotation(arg0 context.Context, arg1 *domain.CreateAnnotationRequest) (*domain.Annotation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAnnotation", arg0, arg1)
	ret0, _ := ret[0].(*domain.Annotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAnnotation indicates an expected call of CreateAnnotation.
func (mr *MockAnnotationServiceMockRecorder) CreateAnnotation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAnnotation", reflect.TypeOf((*MockAnnotationService)(nil).CreateAnnotation), arg0, arg1)
}

// DeleteAnnotation mocks base method.
func (m *MockAnnotationService) DeleteAnnotation(arg0 context.Context, arg1 *domain.DeleteAnnotationRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAnnotation", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAnnotation indicates an expected call of DeleteAnnotation.
func (mr *MockAnnotationServiceMockRecorder) DeleteAnnotation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAnnotation", reflect.TypeOf((*MockAnnotationService)(nil).DeleteAnnotation), arg0, arg1)
}

// GetAnnotation mocks base method.
func (m *MockAnnotationService) GetAnnotation(arg0 context.Context, arg1 *domain.GetAnnotationRequest) (*domain.Annotation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnnotation", arg0, arg1)
	ret0, _ := ret[0].(*domain.Annotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnnotation indicates an expected call of GetAnnotation.
func (mr *MockAnnotationServiceMockRecorder) GetAnnotation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnnotation", reflect.TypeOf((*MockAnnotationService)(nil).GetAnnotation), arg0, arg1)
}

// ListAnnotations mocks base method.
func (m *MockAnnotationService) ListAnnotations(arg0 context.Context, arg1 *domain.ListAnnotationsRequest) ([]*domain.Annotation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAnnotations", arg0, arg1)
	ret0, _ := ret[0].([]*domain.Annotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAnnotations indicates an expected call of ListAnnotations.
func (mr *MockAnnotationServiceMockRecorder) ListAnnotations(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAnnotations", reflect.TypeOf((*MockAnnotationService)(nil).ListAnnotations), arg0, arg1)
}

// UpdateAnnotation mocks base method.
func (m *MockAnnotationService) UpdateAnnotation(arg0 context.Context, arg1 *domain.UpdateAnnotationRequest) (*domain.Annotation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAnnotation", arg0, arg1)
	ret0, _ := ret[0].(*domain.Annotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAnnotation indicates an expected call of UpdateAnnotation.
func (mr *MockAnnotationServiceMockRecorder) UpdateAnnotation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAnnotation", reflect.TypeOf((*MockAnnotationService)(nil).UpdateAnnotation), arg0, arg1)
}
