// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: SESDiscoveryServiceInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockSESDiscoveryServiceInterface is a mock of SESDiscoveryServiceInterface interface.
type MockSESDiscoveryServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSESDiscoveryServiceInterfaceMockRecorder
}

// MockSESDiscoveryServiceInterfaceMockRecorder is the mock recorder for MockSESDiscoveryServiceInterface.
type MockSESDiscoveryServiceInterfaceMockRecorder struct {
	mock *MockSESDiscoveryServiceInterface
}

// NewMockSESDiscoveryServiceInterface creates a new mock instance.
func NewMockSESDiscoveryServiceInterface(ctrl *gomock.Controller) *MockSESDiscoveryServiceInterface {
	mock := &MockSESDiscoveryServiceInterface{ctrl: ctrl}
	mock.recorder = &MockSESDiscoveryServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSESDiscoveryServiceInterface) EXPECT() *MockSESDiscoveryServiceInterfaceMockRecorder {
	return m.recorder
}

// EnableTenantIsolation mocks base method.
func (m *MockSESDiscoveryServiceInterface) EnableTenantIsolation(arg0 context.Context, arg1 domain.EnableSESTenantIsolationRequest) (*domain.SESTenantProvisionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableTenantIsolation", arg0, arg1)
	ret0, _ := ret[0].(*domain.SESTenantProvisionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnableTenantIsolation indicates an expected call of EnableTenantIsolation.
func (mr *MockSESDiscoveryServiceInterfaceMockRecorder) EnableTenantIsolation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableTenantIsolation", reflect.TypeOf((*MockSESDiscoveryServiceInterface)(nil).EnableTenantIsolation), arg0, arg1)
}

// ListConfigurationSets mocks base method.
func (m *MockSESDiscoveryServiceInterface) ListConfigurationSets(arg0 context.Context, arg1 domain.SESCredentialsRef) (*domain.ListSESConfigurationSetsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConfigurationSets", arg0, arg1)
	ret0, _ := ret[0].(*domain.ListSESConfigurationSetsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConfigurationSets indicates an expected call of ListConfigurationSets.
func (mr *MockSESDiscoveryServiceInterfaceMockRecorder) ListConfigurationSets(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConfigurationSets", reflect.TypeOf((*MockSESDiscoveryServiceInterface)(nil).ListConfigurationSets), arg0, arg1)
}

// ListTenants mocks base method.
func (m *MockSESDiscoveryServiceInterface) ListTenants(arg0 context.Context, arg1 domain.SESCredentialsRef) (*domain.ListSESTenantsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTenants", arg0, arg1)
	ret0, _ := ret[0].(*domain.ListSESTenantsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTenants indicates an expected call of ListTenants.
func (mr *MockSESDiscoveryServiceInterfaceMockRecorder) ListTenants(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTenants", reflect.TypeOf((*MockSESDiscoveryServiceInterface)(nil).ListTenants), arg0, arg1)
}

// VerifyTenant mocks base method.
func (m *MockSESDiscoveryServiceInterface) VerifyTenant(arg0 context.Context, arg1 domain.VerifySESTenantRequest) (*domain.SESTenantVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyTenant", arg0, arg1)
	ret0, _ := ret[0].(*domain.SESTenantVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyTenant indicates an expected call of VerifyTenant.
func (mr *MockSESDiscoveryServiceInterfaceMockRecorder) VerifyTenant(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyTenant", reflect.TypeOf((*MockSESDiscoveryServiceInterface)(nil).VerifyTenant), arg0, arg1)
}
