// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: AutomationRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockAutomationRepository is a mock of AutomationRepository interface.
type MockAutomationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAutomationRepositoryMockRecorder
}

// MockAutomationRepositoryMockRecorder is the mock recorder for MockAutomationRepository.
type MockAutomationRepositoryMockRecorder struct {
	mock *MockAutomationRepository
}

// NewMockAutomationRepository creates a new mock instance.
func NewMockAutomationRepository(ctrl *gomock.Controller) *MockAutomationRepository {
	mock := &MockAutomationRepository{ctrl: ctrl}
	mock.recorder = &MockAutomationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAutomationRepository) EXPECT() *MockAutomationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAutomationRepository) Create(arg0 context.Context, arg1 string, arg2 *domain.Automation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAutomationRepositoryMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAutomationRepository)(nil).Create), arg0, arg1, arg2)
}

// CreateAutomationTrigger mocks base method.
func (m *MockAutomationRepository) CreateAutomationTrigger(arg0 context.Context, arg1 string, arg2 *domain.Automation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAutomationTrigger", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAutomationTrigger indicates an expected call of CreateAutomationTrigger.
func (mr *MockAutomationRepositoryMockRecorder) CreateAutomationTrigger(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAutomationTrigger", reflect.TypeOf((*MockAutomationRepository)(nil).CreateAutomationTrigger), arg0, arg1, arg2)
}

// CreateNodeExecution mocks base method.
func (m *MockAutomationRepository) CreateNodeExecution(arg0 context.Context, arg1 string, arg2 *domain.NodeExecution) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNodeExecution", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNodeExecution indicates an expected call of CreateNodeExecution.
func (mr *MockAutomationRepositoryMockRecorder) CreateNodeExecution(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNodeExecution", reflect.TypeOf((*MockAutomationRepository)(nil).CreateNodeExecution), arg0, arg1, arg2)
}

// CreateNodeExecutionTx mocks base method.
func (m *MockAutomationRepository) CreateNodeExecutionTx(arg0 context.Context, arg1 *sql.Tx, arg2 string, arg3 *domain.NodeExecution) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNodeExecutionTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNodeExecutionTx indicates an expected call of CreateNodeExecutionTx.
func (mr *MockAutomationRepositoryMockRecorder) CreateNodeExecutionTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNodeExecutionTx", reflect.TypeOf((*MockAutomationRepository)(nil).CreateNodeExecutionTx), arg0, arg1, arg2, arg3)
}

// CreateTx mocks base method.
func (m *MockAutomationRepository) CreateTx(arg0 context.Context, arg1 *sql.Tx, arg2 string, arg3 *domain.Automation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTx indicates an expected call of CreateTx.
func (mr *MockAutomationRepositoryMockRecorder) CreateTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTx", reflect.TypeOf((*MockAutomationRepository)(nil).CreateTx), arg0, arg1, arg2, arg3)
}

// Delete mocks base method.
func (m *MockAutomationRepository) Delete(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAutomationRepositoryMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAutomationRepository)(nil).Delete), arg0, arg1, arg2)
}

// DeleteTx mocks base method.
func (m *MockAutomationRepository) DeleteTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTx indicates an expected call of DeleteTx.
func (mr *MockAutomationRepositoryMockRecorder) DeleteTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTx", reflect.TypeOf((*MockAutomationRepository)(nil).DeleteTx), arg0, arg1, arg2, arg3)
}

// DropAutomationTrigger mocks base method.
func (m *MockAutomationRepository) DropAutomationTrigger(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropAutomationTrigger", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DropAutomationTrigger indicates an expected call of DropAutomationTrigger.
func (mr *MockAutomationRepositoryMockRecorder) DropAutomationTrigger(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropAutomationTrigger", reflect.TypeOf((*MockAutomationRepository)(nil).DropAutomationTrigger), arg0, arg1, arg2)
}

// ExitContactJourneysOnReply mocks base method.
func (m *MockAutomationRepository) ExitContactJourneysOnReply(arg0 context.Context, arg1, arg2 string, arg3 *string, arg4 string, arg5 time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExitContactJourneysOnReply", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExitContactJourneysOnReply indicates an expected call of ExitContactJourneysOnReply.
func (mr *MockAutomationRepositoryMockRecorder) ExitContactJourneysOnReply(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExitContactJourneysOnReply", reflect.TypeOf((*MockAutomationRepository)(nil).ExitContactJourneysOnReply), arg0, arg1, arg2, arg3, arg4, arg5)
}

// UpdateContactAutomationIfActive mocks base method.
func (m *MockAutomationRepository) UpdateContactAutomationIfActive(arg0 context.Context, arg1 string, arg2 *domain.ContactAutomation) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContactAutomationIfActive", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateContactAutomationIfActive indicates an expected call of UpdateContactAutomationIfActive.
func (mr *MockAutomationRepositoryMockRecorder) UpdateContactAutomationIfActive(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContactAutomationIfActive", reflect.TypeOf((*MockAutomationRepository)(nil).UpdateContactAutomationIfActive), arg0, arg1, arg2)
}

// GetByID mocks base method.
func (m *MockAutomationRepository) GetByID(arg0 context.Context, arg1, arg2 string) (*domain.Automation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Automation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAutomationRepositoryMockRecorder) GetByID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAutomationRepository)(nil).GetByID), arg0, arg1, arg2)
}

// GetByIDTx mocks base method.
func (m *MockAutomationRepository) GetByIDTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string) (*domain.Automation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.Automation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDTx indicates an expected call of GetByIDTx.
func (mr *MockAutomationRepositoryMockRecorder) GetByIDTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDTx", reflect.TypeOf((*MockAutomationRepository)(nil).GetByIDTx), arg0, arg1, arg2, arg3)
}

// GetContactAutomation mocks base method.
func (m *MockAutomationRepository) GetContactAutomation(arg0 context.Context, arg1, arg2 string) (*domain.ContactAutomation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactAutomation", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.ContactAutomation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContactAutomation indicates an expected call of GetContactAutomation.
func (mr *MockAutomationRepositoryMockRecorder) GetContactAutomation(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactAutomation", reflect.TypeOf((*MockAutomationRepository)(nil).GetContactAutomation), arg0, arg1, arg2)
}

// GetContactAutomationByEmail mocks base method.
func (m *MockAutomationRepository) GetContactAutomationByEmail(arg0 context.Context, arg1, arg2, arg3 string) (*domain.ContactAutomation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactAutomationByEmail", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.ContactAutomation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContactAutomationByEmail indicates an expected call of GetContactAutomationByEmail.
func (mr *MockAutomationRepositoryMockRecorder) GetContactAutomationByEmail(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactAutomationByEmail", reflect.TypeOf((*MockAutomationRepository)(nil).GetContactAutomationByEmail), arg0, arg1, arg2, arg3)
}

// GetContactAutomationTx mocks base method.
func (m *MockAutomationRepository) GetContactAutomationTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string) (*domain.ContactAutomation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactAutomationTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.ContactAutomation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContactAutomationTx indicates an expected call of GetContactAutomationTx.
func (mr *MockAutomationRepositoryMockRecorder) GetContactAutomationTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactAutomationTx", reflect.TypeOf((*MockAutomationRepository)(nil).GetContactAutomationTx), arg0, arg1, arg2, arg3)
}

// GetNodeExecutions mocks base method.
func (m *MockAutomationRepository) GetNodeExecutions(arg0 context.Context, arg1, arg2 string) ([]*domain.NodeExecution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeExecutions", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.NodeExecution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeExecutions indicates an expected call of GetNodeExecutions.
func (mr *MockAutomationRepositoryMockRecorder) GetNodeExecutions(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeExecutions", reflect.TypeOf((*MockAutomationRepository)(nil).GetNodeExecutions), arg0, arg1, arg2)
}

// GetScheduledContactAutomations mocks base method.
func (m *MockAutomationRepository) GetScheduledContactAutomations(arg0 context.Context, arg1 string, arg2 time.Time, arg3 int) ([]*domain.ContactAutomation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduledContactAutomations", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.ContactAutomation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduledContactAutomations indicates an expected call of GetScheduledContactAutomations.
func (mr *MockAutomationRepositoryMockRecorder) GetScheduledContactAutomations(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduledContactAutomations", reflect.TypeOf((*MockAutomationRepository)(nil).GetScheduledContactAutomations), arg0, arg1, arg2, arg3)
}

// GetScheduledContactAutomationsGlobal mocks base method.
func (m *MockAutomationRepository) GetScheduledContactAutomationsGlobal(arg0 context.Context, arg1 time.Time, arg2 int) ([]*domain.ContactAutomationWithWorkspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScheduledContactAutomationsGlobal", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.ContactAutomationWithWorkspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduledContactAutomationsGlobal indicates an expected call of GetScheduledContactAutomationsGlobal.
func (mr *MockAutomationRepositoryMockRecorder) GetScheduledContactAutomationsGlobal(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduledContactAutomationsGlobal", reflect.TypeOf((*MockAutomationRepository)(nil).GetScheduledContactAutomationsGlobal), arg0, arg1, arg2)
}

// IncrementAutomationStat mocks base method.
func (m *MockAutomationRepository) IncrementAutomationStat(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAutomationStat", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementAutomationStat indicates an expected call of IncrementAutomationStat.
func (mr *MockAutomationRepositoryMockRecorder) IncrementAutomationStat(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAutomationStat", reflect.TypeOf((*MockAutomationRepository)(nil).IncrementAutomationStat), arg0, arg1, arg2, arg3)
}

// List mocks base method.
func (m *MockAutomationRepository) List(arg0 context.Context, arg1 string, arg2 domain.AutomationFilter) ([]*domain.Automation, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.Automation)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockAutomationRepositoryMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAutomationRepository)(nil).List), arg0, arg1, arg2)
}

// ListContactAutomations mocks base method.
func (m *MockAutomationRepository) ListContactAutomations(arg0 context.Context, arg1 string, arg2 domain.ContactAutomationFilter) ([]*domain.ContactAutomation, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContactAutomations", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.ContactAutomation)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListContactAutomations indicates an expected call of ListContactAutomations.
func (mr *MockAutomationRepositoryMockRecorder) ListContactAutomations(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContactAutomations", reflect.TypeOf((*MockAutomationRepository)(nil).ListContactAutomations), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockAutomationRepository) Update(arg0 context.Context, arg1 string, arg2 *domain.Automation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAutomationRepositoryMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAutomationRepository)(nil).Update), arg0, arg1, arg2)
}

// UpdateAutomationStats mocks base method.
func (m *MockAutomationRepository) UpdateAutomationStats(arg0 context.Context, arg1, arg2 string, arg3 *domain.AutomationStats) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAutomationStats", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAutomationStats indicates an expected call of UpdateAutomationStats.
func (mr *MockAutomationRepositoryMockRecorder) UpdateAutomationStats(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAutomationStats", reflect.TypeOf((*MockAutomationRepository)(nil).UpdateAutomationStats), arg0, arg1, arg2, arg3)
}

// UpdateAutomationStatsTx mocks base method.
func (m *MockAutomationRepository) UpdateAutomationStatsTx(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 string, arg4 *domain.AutomationStats) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAutomationStatsTx", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAutomationStatsTx indicates an expected call of UpdateAutomationStatsTx.
func (mr *MockAutomationRepositoryMockRecorder) UpdateAutomationStatsTx(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAutomationStatsTx", reflect.TypeOf((*MockAutomationRepository)(nil).UpdateAutomationStatsTx), arg0, arg1, arg2, arg3, arg4)
}

// UpdateContactAutomation mocks base method.
func (m *MockAutomationRepository) UpdateContactAutomation(arg0 context.Context, arg1 string, arg2 *domain.ContactAutomation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContactAutomation", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateContactAutomation indicates an expected call of UpdateContactAutomation.
func (mr *MockAutomationRepositoryMockRecorder) UpdateContactAutomation(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContactAutomation", reflect.TypeOf((*MockAutomationRepository)(nil).UpdateContactAutomation), arg0, arg1, arg2)
}

// UpdateContactAutomationTx mocks base method.
func (m *MockAutomationRepository) UpdateContactAutomationTx(arg0 context.Context, arg1 *sql.Tx, arg2 string, arg3 *domain.ContactAutomation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContactAutomationTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateContactAutomationTx indicates an expected call of UpdateContactAutomationTx.
func (mr *MockAutomationRepositoryMockRecorder) UpdateContactAutomationTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContactAutomationTx", reflect.TypeOf((*MockAutomationRepository)(nil).UpdateContactAutomationTx), arg0, arg1, arg2, arg3)
}

// UpdateNodeExecution mocks base method.
func (m *MockAutomationRepository) UpdateNodeExecution(arg0 context.Context, arg1 string, arg2 *domain.NodeExecution) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNodeExecution", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNodeExecution indicates an expected call of UpdateNodeExecution.
func (mr *MockAutomationRepositoryMockRecorder) UpdateNodeExecution(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNodeExecution", reflect.TypeOf((*MockAutomationRepository)(nil).UpdateNodeExecution), arg0, arg1, arg2)
}

// UpdateNodeExecutionTx mocks base method.
func (m *MockAutomationRepository) UpdateNodeExecutionTx(arg0 context.Context, arg1 *sql.Tx, arg2 string, arg3 *domain.NodeExecution) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNodeExecutionTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNodeExecutionTx indicates an expected call of UpdateNodeExecutionTx.
func (mr *MockAutomationRepositoryMockRecorder) UpdateNodeExecutionTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNodeExecutionTx", reflect.TypeOf((*MockAutomationRepository)(nil).UpdateNodeExecutionTx), arg0, arg1, arg2, arg3)
}

// UpdateTx mocks base method.
func (m *MockAutomationRepository) UpdateTx(arg0 context.Context, arg1 *sql.Tx, arg2 string, arg3 *domain.Automation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTx indicates an expected call of UpdateTx.
func (mr *MockAutomationRepositoryMockRecorder) UpdateTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTx", reflect.TypeOf((*MockAutomationRepository)(nil).UpdateTx), arg0, arg1, arg2, arg3)
}

// WithTransaction mocks base method.
func (m *MockAutomationRepository) WithTransaction(arg0 context.Context, arg1 func(*sql.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockAutomationRepositoryMockRecorder) WithTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockAutomationRepository)(nil).WithTransaction), arg0, arg1)
}
