// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: CustomEventRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockCustomEventRepository is a mock of CustomEventRepository interface.
type MockCustomEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomEventRepositoryMockRecorder
}

// MockCustomEventRepositoryMockRecorder is the mock recorder for MockCustomEventRepository.
type MockCustomEventRepositoryMockRecorder struct {
	mock *MockCustomEventRepository
}

// NewMockCustomEventRepository creates a new mock instance.
func NewMockCustomEventRepository(ctrl *gomock.Controller) *MockCustomEventRepository {
	mock := &MockCustomEventRepository{ctrl: ctrl}
	mock.recorder = &MockCustomEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomEventRepository) EXPECT() *MockCustomEventRepositoryMockRecorder {
	return m.recorder
}

// BatchInsertNew mocks base method.
func (m *MockCustomEventRepository) BatchInsertNew(arg0 context.Context, arg1 string, arg2 []*domain.CustomEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInsertNew", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchInsertNew indicates an expected call of BatchInsertNew.
func (mr *MockCustomEventRepositoryMockRecorder) BatchInsertNew(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsertNew", reflect.TypeOf((*MockCustomEventRepository)(nil).BatchInsertNew), arg0, arg1, arg2)
}

// BatchUpsert mocks base method.
func (m *MockCustomEventRepository) BatchUpsert(arg0 context.Context, arg1 string, arg2 []*domain.CustomEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpsert", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchUpsert indicates an expected call of BatchUpsert.
func (mr *MockCustomEventRepositoryMockRecorder) BatchUpsert(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpsert", reflect.TypeOf((*MockCustomEventRepository)(nil).BatchUpsert), arg0, arg1, arg2)
}

// DeleteForEmail mocks base method.
func (m *MockCustomEventRepository) DeleteForEmail(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteForEmail", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteForEmail indicates an expected call of DeleteForEmail.
func (mr *MockCustomEventRepositoryMockRecorder) DeleteForEmail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteForEmail", reflect.TypeOf((*MockCustomEventRepository)(nil).DeleteForEmail), arg0, arg1, arg2)
}

// GetByID mocks base method.
func (m *MockCustomEventRepository) GetByID(arg0 context.Context, arg1, arg2, arg3 string) (*domain.CustomEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.CustomEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCustomEventRepositoryMockRecorder) GetByID(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCustomEventRepository)(nil).GetByID), arg0, arg1, arg2, arg3)
}

// ListByEmail mocks base method.
func (m *MockCustomEventRepository) ListByEmail(arg0 context.Context, arg1, arg2 string, arg3, arg4 int) ([]*domain.CustomEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEmail", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*domain.CustomEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByEmail indicates an expected call of ListByEmail.
func (mr *MockCustomEventRepositoryMockRecorder) ListByEmail(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEmail", reflect.TypeOf((*MockCustomEventRepository)(nil).ListByEmail), arg0, arg1, arg2, arg3, arg4)
}

// ListByEventName mocks base method.
func (m *MockCustomEventRepository) ListByEventName(arg0 context.Context, arg1, arg2 string, arg3, arg4 int) ([]*domain.CustomEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEventName", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*domain.CustomEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByEventName indicates an expected call of ListByEventName.
func (mr *MockCustomEventRepositoryMockRecorder) ListByEventName(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEventName", reflect.TypeOf((*MockCustomEventRepository)(nil).ListByEventName), arg0, arg1, arg2, arg3, arg4)
}

// Upsert mocks base method.
func (m *MockCustomEventRepository) Upsert(arg0 context.Context, arg1 string, arg2 *domain.CustomEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockCustomEventRepositoryMockRecorder) Upsert(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockCustomEventRepository)(nil).Upsert), arg0, arg1, arg2)
}
