// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: WebAnalyticsService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockWebAnalyticsService is a mock of WebAnalyticsService interface.
type MockWebAnalyticsService struct {
	ctrl     *gomock.Controller
	recorder *MockWebAnalyticsServiceMockRecorder
}

// MockWebAnalyticsServiceMockRecorder is the mock recorder for MockWebAnalyticsService.
type MockWebAnalyticsServiceMockRecorder struct {
	mock *MockWebAnalyticsService
}

// NewMockWebAnalyticsService creates a new mock instance.
func NewMockWebAnalyticsService(ctrl *gomock.Controller) *MockWebAnalyticsService {
	mock := &MockWebAnalyticsService{ctrl: ctrl}
	mock.recorder = &MockWebAnalyticsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebAnalyticsService) EXPECT() *MockWebAnalyticsServiceMockRecorder {
	return m.recorder
}

// BackfillCancel mocks base method.
func (m *MockWebAnalyticsService) BackfillCancel(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackfillCancel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BackfillCancel indicates an expected call of BackfillCancel.
func (mr *MockWebAnalyticsServiceMockRecorder) BackfillCancel(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackfillCancel", reflect.TypeOf((*MockWebAnalyticsService)(nil).BackfillCancel), arg0, arg1)
}

// BackfillStart mocks base method.
func (m *MockWebAnalyticsService) BackfillStart(arg0 context.Context, arg1 string) (*domain.WebAnalyticsBackfillStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackfillStart", arg0, arg1)
	ret0, _ := ret[0].(*domain.WebAnalyticsBackfillStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BackfillStart indicates an expected call of BackfillStart.
func (mr *MockWebAnalyticsServiceMockRecorder) BackfillStart(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackfillStart", reflect.TypeOf((*MockWebAnalyticsService)(nil).BackfillStart), arg0, arg1)
}

// BackfillStatus mocks base method.
func (m *MockWebAnalyticsService) BackfillStatus(arg0 context.Context, arg1 string) (*domain.WebAnalyticsBackfillStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackfillStatus", arg0, arg1)
	ret0, _ := ret[0].(*domain.WebAnalyticsBackfillStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BackfillStatus indicates an expected call of BackfillStatus.
func (mr *MockWebAnalyticsServiceMockRecorder) BackfillStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackfillStatus", reflect.TypeOf((*MockWebAnalyticsService)(nil).BackfillStatus), arg0, arg1)
}

// Track mocks base method.
func (m *MockWebAnalyticsService) Track(arg0 context.Context, arg1 *domain.WebTrackPayload, arg2 domain.WebRequestMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Track", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Track indicates an expected call of Track.
func (mr *MockWebAnalyticsServiceMockRecorder) Track(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Track", reflect.TypeOf((*MockWebAnalyticsService)(nil).Track), arg0, arg1, arg2)
}
