// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: GeoIPResolver)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockGeoIPResolver is a mock of GeoIPResolver interface.
type MockGeoIPResolver struct {
	ctrl     *gomock.Controller
	recorder *MockGeoIPResolverMockRecorder
}

// MockGeoIPResolverMockRecorder is the mock recorder for MockGeoIPResolver.
type MockGeoIPResolverMockRecorder struct {
	mock *MockGeoIPResolver
}

// NewMockGeoIPResolver creates a new mock instance.
func NewMockGeoIPResolver(ctrl *gomock.Controller) *MockGeoIPResolver {
	mock := &MockGeoIPResolver{ctrl: ctrl}
	mock.recorder = &MockGeoIPResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeoIPResolver) EXPECT() *MockGeoIPResolverMockRecorder {
	return m.recorder
}

// Lookup mocks base method.
func (m *MockGeoIPResolver) Lookup(arg0 string) (*domain.WebGeoResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lookup", arg0)
	ret0, _ := ret[0].(*domain.WebGeoResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lookup indicates an expected call of Lookup.
func (mr *MockGeoIPResolverMockRecorder) Lookup(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lookup", reflect.TypeOf((*MockGeoIPResolver)(nil).Lookup), arg0)
}
