// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: WebAnalyticsRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockWebAnalyticsRepository is a mock of WebAnalyticsRepository interface.
type MockWebAnalyticsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWebAnalyticsRepositoryMockRecorder
}

// MockWebAnalyticsRepositoryMockRecorder is the mock recorder for MockWebAnalyticsRepository.
type MockWebAnalyticsRepositoryMockRecorder struct {
	mock *MockWebAnalyticsRepository
}

// NewMockWebAnalyticsRepository creates a new mock instance.
func NewMockWebAnalyticsRepository(ctrl *gomock.Controller) *MockWebAnalyticsRepository {
	mock := &MockWebAnalyticsRepository{ctrl: ctrl}
	mock.recorder = &MockWebAnalyticsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebAnalyticsRepository) EXPECT() *MockWebAnalyticsRepositoryMockRecorder {
	return m.recorder
}

// AnalyzePartitions mocks base method.
func (m *MockWebAnalyticsRepository) AnalyzePartitions(arg0 context.Context, arg1 string, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnalyzePartitions", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnalyzePartitions indicates an expected call of AnalyzePartitions.
func (mr *MockWebAnalyticsRepositoryMockRecorder) AnalyzePartitions(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyzePartitions", reflect.TypeOf((*MockWebAnalyticsRepository)(nil).AnalyzePartitions), arg0, arg1, arg2)
}

// AnonymizeContact mocks base method.
func (m *MockWebAnalyticsRepository) AnonymizeContact(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnonymizeContact", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnonymizeContact indicates an expected call of AnonymizeContact.
func (mr *MockWebAnalyticsRepositoryMockRecorder) AnonymizeContact(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnonymizeContact", reflect.TypeOf((*MockWebAnalyticsRepository)(nil).AnonymizeContact), arg0, arg1, arg2)
}

// BackfillPartition mocks base method.
func (m *MockWebAnalyticsRepository) BackfillPartition(arg0 context.Context, arg1, arg2 string, arg3 []domain.WebFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackfillPartition", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BackfillPartition indicates an expected call of BackfillPartition.
func (mr *MockWebAnalyticsRepositoryMockRecorder) BackfillPartition(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackfillPartition", reflect.TypeOf((*MockWebAnalyticsRepository)(nil).BackfillPartition), arg0, arg1, arg2, arg3)
}

// EnsureMonthlyPartitions mocks base method.
func (m *MockWebAnalyticsRepository) EnsureMonthlyPartitions(arg0 context.Context, arg1 string, arg2 []time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureMonthlyPartitions", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureMonthlyPartitions indicates an expected call of EnsureMonthlyPartitions.
func (mr *MockWebAnalyticsRepositoryMockRecorder) EnsureMonthlyPartitions(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureMonthlyPartitions", reflect.TypeOf((*MockWebAnalyticsRepository)(nil).EnsureMonthlyPartitions), arg0, arg1, arg2)
}

// FlushBatch mocks base method.
func (m *MockWebAnalyticsRepository) FlushBatch(arg0 context.Context, arg1 string, arg2 []*domain.WebSession, arg3 []*domain.WebPage, arg4 []*domain.WebGoal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushBatch", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// FlushBatch indicates an expected call of FlushBatch.
func (mr *MockWebAnalyticsRepositoryMockRecorder) FlushBatch(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushBatch", reflect.TypeOf((*MockWebAnalyticsRepository)(nil).FlushBatch), arg0, arg1, arg2, arg3, arg4)
}

// GetUsage mocks base method.
func (m *MockWebAnalyticsRepository) GetUsage(arg0 context.Context, arg1 string, arg2 []time.Time) ([]*domain.MonthlyUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsage", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.MonthlyUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsage indicates an expected call of GetUsage.
func (mr *MockWebAnalyticsRepositoryMockRecorder) GetUsage(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsage", reflect.TypeOf((*MockWebAnalyticsRepository)(nil).GetUsage), arg0, arg1, arg2)
}

// ListPartitions mocks base method.
func (m *MockWebAnalyticsRepository) ListPartitions(arg0 context.Context, arg1, arg2 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPartitions", arg0, arg1, arg2)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPartitions indicates an expected call of ListPartitions.
func (mr *MockWebAnalyticsRepositoryMockRecorder) ListPartitions(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPartitions", reflect.TypeOf((*MockWebAnalyticsRepository)(nil).ListPartitions), arg0, arg1, arg2)
}

// ProjectContactNavigation mocks base method.
func (m *MockWebAnalyticsRepository) ProjectContactNavigation(arg0 context.Context, arg1 string, arg2 []*domain.WebSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectContactNavigation", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProjectContactNavigation indicates an expected call of ProjectContactNavigation.
func (mr *MockWebAnalyticsRepositoryMockRecorder) ProjectContactNavigation(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectContactNavigation", reflect.TypeOf((*MockWebAnalyticsRepository)(nil).ProjectContactNavigation), arg0, arg1, arg2)
}

// RecomputeUsage mocks base method.
func (m *MockWebAnalyticsRepository) RecomputeUsage(arg0 context.Context, arg1 string, arg2 time.Time, arg3 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecomputeUsage", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecomputeUsage indicates an expected call of RecomputeUsage.
func (mr *MockWebAnalyticsRepositoryMockRecorder) RecomputeUsage(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecomputeUsage", reflect.TypeOf((*MockWebAnalyticsRepository)(nil).RecomputeUsage), arg0, arg1, arg2, arg3)
}

// SetPartitionAutovacuum mocks base method.
func (m *MockWebAnalyticsRepository) SetPartitionAutovacuum(arg0 context.Context, arg1, arg2 string, arg3 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPartitionAutovacuum", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPartitionAutovacuum indicates an expected call of SetPartitionAutovacuum.
func (mr *MockWebAnalyticsRepositoryMockRecorder) SetPartitionAutovacuum(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPartitionAutovacuum", reflect.TypeOf((*MockWebAnalyticsRepository)(nil).SetPartitionAutovacuum), arg0, arg1, arg2, arg3)
}
