// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: AnnotationRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockAnnotationRepository is a mock of AnnotationRepository interface.
type MockAnnotationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnnotationRepositoryMockRecorder
}

// MockAnnotationRepositoryMockRecorder is the mock recorder for MockAnnotationRepository.
type MockAnnotationRepositoryMockRecorder struct {
	mock *MockAnnotationRepository
}

// NewMockAnnotationRepository creates a new mock instance.
func NewMockAnnotationRepository(ctrl *gomock.Controller) *MockAnnotationRepository {
	mock := &MockAnnotationRepository{ctrl: ctrl}
	mock.recorder = &MockAnnotationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnnotationRepository) EXPECT() *MockAnnotationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAnnotationRepository) Create(arg0 context.Context, arg1 string, arg2 *domain.Annotation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAnnotationRepositoryMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAnnotationRepository)(nil).Create), arg0, arg1, arg2)
}

// CreateFromSource mocks base method.
func (m *MockAnnotationRepository) CreateFromSource(arg0 context.Context, arg1 string, arg2 *domain.Annotation) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFromSource", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFromSource indicates an expected call of CreateFromSource.
func (mr *MockAnnotationRepositoryMockRecorder) CreateFromSource(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFromSource", reflect.TypeOf((*MockAnnotationRepository)(nil).CreateFromSource), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockAnnotationRepository) Delete(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAnnotationRepositoryMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAnnotationRepository)(nil).Delete), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockAnnotationRepository) Get(arg0 context.Context, arg1, arg2 string) (*domain.Annotation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Annotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAnnotationRepositoryMockRecorder) Get(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAnnotationRepository)(nil).Get), arg0, arg1, arg2)
}

// List mocks base method.
func (m *MockAnnotationRepository) List(arg0 context.Context, arg1 string, arg2 domain.AnnotationFilter) ([]*domain.Annotation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.Annotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAnnotationRepositoryMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAnnotationRepository)(nil).List), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockAnnotationRepository) Update(arg0 context.Context, arg1 string, arg2 *domain.Annotation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAnnotationRepositoryMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAnnotationRepository)(nil).Update), arg0, arg1, arg2)
}
