// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: EmailQueueRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockEmailQueueRepository is a mock of EmailQueueRepository interface.
type MockEmailQueueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailQueueRepositoryMockRecorder
}

// MockEmailQueueRepositoryMockRecorder is the mock recorder for MockEmailQueueRepository.
type MockEmailQueueRepositoryMockRecorder struct {
	mock *MockEmailQueueRepository
}

// NewMockEmailQueueRepository creates a new mock instance.
func NewMockEmailQueueRepository(ctrl *gomock.Controller) *MockEmailQueueRepository {
	mock := &MockEmailQueueRepository{ctrl: ctrl}
	mock.recorder = &MockEmailQueueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailQueueRepository) EXPECT() *MockEmailQueueRepositoryMockRecorder {
	return m.recorder
}

// CountBySourceAndStatus mocks base method.
func (m *MockEmailQueueRepository) CountBySourceAndStatus(arg0 context.Context, arg1 string, arg2 domain.EmailQueueSourceType, arg3 string, arg4 domain.EmailQueueStatus) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBySourceAndStatus", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBySourceAndStatus indicates an expected call of CountBySourceAndStatus.
func (mr *MockEmailQueueRepositoryMockRecorder) CountBySourceAndStatus(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBySourceAndStatus", reflect.TypeOf((*MockEmailQueueRepository)(nil).CountBySourceAndStatus), arg0, arg1, arg2, arg3, arg4)
}

// Delete mocks base method.
func (m *MockEmailQueueRepository) Delete(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEmailQueueRepositoryMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEmailQueueRepository)(nil).Delete), arg0, arg1, arg2)
}

// DeleteBySource mocks base method.
func (m *MockEmailQueueRepository) DeleteBySource(arg0 context.Context, arg1 string, arg2 domain.EmailQueueSourceType, arg3 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBySource", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBySource indicates an expected call of DeleteBySource.
func (mr *MockEmailQueueRepositoryMockRecorder) DeleteBySource(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBySource", reflect.TypeOf((*MockEmailQueueRepository)(nil).DeleteBySource), arg0, arg1, arg2, arg3)
}

// DeleteBySourceTx mocks base method.
func (m *MockEmailQueueRepository) DeleteBySourceTx(arg0 context.Context, arg1 *sql.Tx, arg2 domain.EmailQueueSourceType, arg3 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBySourceTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBySourceTx indicates an expected call of DeleteBySourceTx.
func (mr *MockEmailQueueRepositoryMockRecorder) DeleteBySourceTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBySourceTx", reflect.TypeOf((*MockEmailQueueRepository)(nil).DeleteBySourceTx), arg0, arg1, arg2, arg3)
}

// DeleteForEmail mocks base method.
func (m *MockEmailQueueRepository) DeleteForEmail(arg0 context.Context, arg1, arg2 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteForEmail", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteForEmail indicates an expected call of DeleteForEmail.
func (mr *MockEmailQueueRepositoryMockRecorder) DeleteForEmail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteForEmail", reflect.TypeOf((*MockEmailQueueRepository)(nil).DeleteForEmail), arg0, arg1, arg2)
}

// Enqueue mocks base method.
func (m *MockEmailQueueRepository) Enqueue(arg0 context.Context, arg1 string, arg2 []*domain.EmailQueueEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockEmailQueueRepositoryMockRecorder) Enqueue(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockEmailQueueRepository)(nil).Enqueue), arg0, arg1, arg2)
}

// EnqueueTx mocks base method.
func (m *MockEmailQueueRepository) EnqueueTx(arg0 context.Context, arg1 *sql.Tx, arg2 []*domain.EmailQueueEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueTx indicates an expected call of EnqueueTx.
func (mr *MockEmailQueueRepositoryMockRecorder) EnqueueTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueTx", reflect.TypeOf((*MockEmailQueueRepository)(nil).EnqueueTx), arg0, arg1, arg2)
}

// FetchPending mocks base method.
func (m *MockEmailQueueRepository) FetchPending(arg0 context.Context, arg1 string, arg2 int) ([]*domain.EmailQueueEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPending", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.EmailQueueEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPending indicates an expected call of FetchPending.
func (mr *MockEmailQueueRepositoryMockRecorder) FetchPending(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPending", reflect.TypeOf((*MockEmailQueueRepository)(nil).FetchPending), arg0, arg1, arg2)
}

// GetBySourceID mocks base method.
func (m *MockEmailQueueRepository) GetBySourceID(arg0 context.Context, arg1 string, arg2 domain.EmailQueueSourceType, arg3 string) ([]*domain.EmailQueueEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySourceID", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*domain.EmailQueueEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySourceID indicates an expected call of GetBySourceID.
func (mr *MockEmailQueueRepositoryMockRecorder) GetBySourceID(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySourceID", reflect.TypeOf((*MockEmailQueueRepository)(nil).GetBySourceID), arg0, arg1, arg2, arg3)
}

// GetStats mocks base method.
func (m *MockEmailQueueRepository) GetStats(arg0 context.Context, arg1 string) (*domain.EmailQueueStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", arg0, arg1)
	ret0, _ := ret[0].(*domain.EmailQueueStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockEmailQueueRepositoryMockRecorder) GetStats(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockEmailQueueRepository)(nil).GetStats), arg0, arg1)
}

// MarkAsFailed mocks base method.
func (m *MockEmailQueueRepository) MarkAsFailed(arg0 context.Context, arg1, arg2, arg3 string, arg4 *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsFailed", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsFailed indicates an expected call of MarkAsFailed.
func (mr *MockEmailQueueRepositoryMockRecorder) MarkAsFailed(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsFailed", reflect.TypeOf((*MockEmailQueueRepository)(nil).MarkAsFailed), arg0, arg1, arg2, arg3, arg4)
}

// MarkAsProcessing mocks base method.
func (m *MockEmailQueueRepository) MarkAsProcessing(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsProcessing", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsProcessing indicates an expected call of MarkAsProcessing.
func (mr *MockEmailQueueRepositoryMockRecorder) MarkAsProcessing(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsProcessing", reflect.TypeOf((*MockEmailQueueRepository)(nil).MarkAsProcessing), arg0, arg1, arg2)
}

// MarkAsSent mocks base method.
func (m *MockEmailQueueRepository) MarkAsSent(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsSent", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsSent indicates an expected call of MarkAsSent.
func (mr *MockEmailQueueRepositoryMockRecorder) MarkAsSent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsSent", reflect.TypeOf((*MockEmailQueueRepository)(nil).MarkAsSent), arg0, arg1, arg2)
}

// PauseBySource mocks base method.
func (m *MockEmailQueueRepository) PauseBySource(arg0 context.Context, arg1 string, arg2 domain.EmailQueueSourceType, arg3 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseBySource", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PauseBySource indicates an expected call of PauseBySource.
func (mr *MockEmailQueueRepositoryMockRecorder) PauseBySource(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseBySource", reflect.TypeOf((*MockEmailQueueRepository)(nil).PauseBySource), arg0, arg1, arg2, arg3)
}

// PauseBySourceTx mocks base method.
func (m *MockEmailQueueRepository) PauseBySourceTx(arg0 context.Context, arg1 *sql.Tx, arg2 domain.EmailQueueSourceType, arg3 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseBySourceTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PauseBySourceTx indicates an expected call of PauseBySourceTx.
func (mr *MockEmailQueueRepositoryMockRecorder) PauseBySourceTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseBySourceTx", reflect.TypeOf((*MockEmailQueueRepository)(nil).PauseBySourceTx), arg0, arg1, arg2, arg3)
}

// ResumeBySource mocks base method.
func (m *MockEmailQueueRepository) ResumeBySource(arg0 context.Context, arg1 string, arg2 domain.EmailQueueSourceType, arg3 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeBySource", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumeBySource indicates an expected call of ResumeBySource.
func (mr *MockEmailQueueRepositoryMockRecorder) ResumeBySource(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeBySource", reflect.TypeOf((*MockEmailQueueRepository)(nil).ResumeBySource), arg0, arg1, arg2, arg3)
}

// ResumeBySourceTx mocks base method.
func (m *MockEmailQueueRepository) ResumeBySourceTx(arg0 context.Context, arg1 *sql.Tx, arg2 domain.EmailQueueSourceType, arg3 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeBySourceTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumeBySourceTx indicates an expected call of ResumeBySourceTx.
func (mr *MockEmailQueueRepositoryMockRecorder) ResumeBySourceTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeBySourceTx", reflect.TypeOf((*MockEmailQueueRepository)(nil).ResumeBySourceTx), arg0, arg1, arg2, arg3)
}

// SetNextRetry mocks base method.
func (m *MockEmailQueueRepository) SetNextRetry(arg0 context.Context, arg1, arg2 string, arg3 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNextRetry", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNextRetry indicates an expected call of SetNextRetry.
func (mr *MockEmailQueueRepositoryMockRecorder) SetNextRetry(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNextRetry", reflect.TypeOf((*MockEmailQueueRepository)(nil).SetNextRetry), arg0, arg1, arg2, arg3)
}
