import type { LLMMessage } from '../../services/api/llm'
import type { ChatMessage, ToolResult } from './types'

// Model-facing text. NOT translated — these strings are read by the LLM, never by the
// user (console/CLAUDE.md's i18n rules cover user-facing strings only).
export const TOOL_RESULTS_HEADER =
  'TOOL RESULTS - automatic message from the application, not typed by the user.'
export const TOOL_RESULTS_FOOTER =
  'Use these results to answer the last user question. Call a tool again only if you still ' +
  'need data you do not have; never repeat a call with identical input. Otherwise answer now, in prose.'
// Paste into a feature system prompt so the model understands the convention.
export const TOOL_RESULT_PROTOCOL_PROMPT =
  `When you call a tool, its output comes back in the NEXT user message, prefixed ` +
  `"${TOOL_RESULTS_HEADER}" and wrapped in <tool_results> tags. That message is generated by the ` +
  `application - never address it as if the user typed it, and never write <tool_results> yourself. ` +
  `Each entry carries call_id, tool, input, and either result or error.`

export const MAX_RESULT_CHARS_PER_TOOL = 6000
export const MAX_RESULT_CHARS_PER_ROUND = 12000
export const MAX_INPUT_ECHO_CHARS = 500

export interface SettledToolCall {
  id: string
  name: string
  input: Record<string, unknown>
  result: ToolResult
}

/** Truncate without splitting a surrogate pair, and always say how much was cut. */
export function clip(text: string, max: number): string {
  if (max <= 0) return `[omitted: ${text.length} chars, payload limit reached]`
  if (text.length <= max) return text
  let cut = text.slice(0, max)
  const last = cut.charCodeAt(cut.length - 1)
  if (last >= 0xd800 && last <= 0xdbff) cut = cut.slice(0, -1)
  return `${cut}...[truncated, ${text.length - cut.length} more chars]`
}

/** Key-order stable, so a model that reorders JSON keys still dedupes. */
export function stableStringify(value: unknown): string {
  if (value === null || typeof value !== 'object') return JSON.stringify(value) ?? 'null'
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(',')}]`
  const obj = value as Record<string, unknown>
  return `{${Object.keys(obj)
    .sort()
    .map((k) => `${JSON.stringify(k)}:${stableStringify(obj[k])}`)
    .join(',')}}`
}

/**
 * Byte-identical to the inline filter/map that used to live in handleSend: tool
 * bubbles and empty messages never go on the wire.
 */
export function toWireMessages(messages: ChatMessage[]): LLMMessage[] {
  return messages
    .filter((m) => m.role !== 'tool' && m.content.trim())
    .map((m) => ({ role: m.role as 'user' | 'assistant', content: m.content }))
}

/**
 * The safety net. internal/domain/llm.go Validate rejects empty content, and every
 * provider maps messages POSITIONALLY with no merging (internal/service/llm_service.go
 * :188-195, same shape in the OpenAI and Gemini paths), so a transcript with an empty
 * turn or two consecutive same-role turns reaches the provider as an invalid request.
 *
 * That is reachable without any continuation: a turn whose only output was tool calls
 * leaves no assistant message in state (insertToolMessage replaces the empty assistant
 * bubble), the tool row is filtered out, and the next turn sends [user, user].
 */
export function normalizeWire(turns: LLMMessage[]): LLMMessage[] {
  const out: LLMMessage[] = []
  for (const turn of turns) {
    const content = turn.content.trim()
    if (!content) continue
    const last = out[out.length - 1]
    if (last && last.role === turn.role) {
      out[out.length - 1] = { role: last.role, content: `${last.content}\n\n${content}` }
      continue
    }
    out.push({ role: turn.role, content })
  }
  while (out.length > 0 && out[0].role !== 'user') out.shift()
  return out
}

/** Fallback assistant turn for a round whose model output was tool calls and no text. */
export function describeCalls(calls: SettledToolCall[]): string {
  return `(Calling ${calls.map((c) => c.name).join(', ')}.)`
}

function safeInput(input: Record<string, unknown>): unknown {
  const json = stableStringify(input)
  return json.length <= MAX_INPUT_ECHO_CHARS
    ? input
    : { _truncated: clip(json, MAX_INPUT_ECHO_CHARS) }
}

/**
 * One user turn carrying EVERY result of the round, as a JSON array.
 *
 * Containment is NOT free from JSON.stringify, which leaves `<` alone: a result row
 * holding the literal text `</tool_results>` would be emitted verbatim and could close
 * the block early, so the model would read the rest of the row as instructions rather
 * than as data. Result rows carry attacker-influenced text as a matter of course - a
 * page path, a referrer, a UTM value, all of them written by whoever linked to the
 * site - so this is the ordinary case, not a contrived one.
 *
 * Escaping every `<` as its < form is what actually closes it. JSON structural
 * characters are {}[],:" and whitespace, so a `<` can only ever occur inside a string
 * literal; the escape is therefore always valid JSON, decodes to the identical value,
 * and leaves no `<` anywhere in the payload for a tag boundary to be forged from.
 */
export function encodeToolResults(calls: SettledToolCall[]): string {
  let budget = MAX_RESULT_CHARS_PER_ROUND
  const entries = calls.map((c) => {
    const base = { call_id: c.id, tool: c.name, input: safeInput(c.input) }
    if (c.result.isError) return { ...base, ok: false, error: clip(c.result.content, 500) }
    const body = clip(c.result.content, Math.min(MAX_RESULT_CHARS_PER_TOOL, budget))
    budget -= body.length
    return { ...base, ok: true, result: body }
  })
  return [
    TOOL_RESULTS_HEADER,
    '<tool_results>',
    JSON.stringify(entries).replace(/</g, '\\u003c'),
    '</tool_results>',
    TOOL_RESULTS_FOOTER
  ].join('\n')
}
