package schema

// AutomationEnrollContactFunction returns the function every installed automation trigger
// calls to enrol a contact.
//
// It lives here for the same reason the webhook trigger body does: the new-workspace path
// (internal/database/init.go) and the v38 migration both install it, and a body that drifts
// between them makes a fresh install behave differently from an upgraded one for identical
// data. internal/migrations/v20.go, v21.go and v25.go carry the ORIGINAL bodies and must stay
// frozen — a historical migration has to keep reproducing the behaviour it shipped.
//
// The signature is load-bearing: the per-automation trigger functions generated by
// internal/service/automation_trigger_generator.go call this by name with these four
// arguments, and every trigger already installed in every workspace keeps calling the old
// signature until it is regenerated. Changing it would abort the contact_timeline insert
// that fired the trigger — which is every contact, list, message-history, custom-event and
// inbound-webhook write in the workspace.
func AutomationEnrollContactFunction() string {
	return `CREATE OR REPLACE FUNCTION automation_enroll_contact(
			p_automation_id VARCHAR(36),
			p_contact_email VARCHAR(255),
			p_root_node_id VARCHAR(36),
			p_frequency VARCHAR(20)
		) RETURNS VOID AS $$
		DECLARE
			v_already_triggered BOOLEAN;
			v_new_id VARCHAR(36);
		BEGIN
			-- 0. Enrol only while the automation is actually running.
			--
			-- The trigger can outlive that: Pause drops it only after writing the status,
			-- Delete discards a failed drop, and two admins transitioning at once can leave
			-- it installed against a paused or draft row. Nothing detects any of those — the
			-- scheduler and the executor filter on status, so no message is ever sent, while
			-- the journeys, timeline events and enrolled stats pile up unnoticed and thaw all
			-- at once the day someone activates the automation again.
			--
			-- Ahead of every write, including the 'once' dedup row: that row is permanent and
			-- nothing ever deletes it, so recording one here would bar the contact from the
			-- automation for good once it is live again.
			IF NOT EXISTS (
				SELECT 1 FROM automations
				WHERE id = p_automation_id
				  AND status = 'live'
				  AND deleted_at IS NULL
			) THEN
				RETURN;
			END IF;

			-- 1. For "once" frequency, check if already triggered
			IF p_frequency = 'once' THEN
				SELECT EXISTS(
					SELECT 1 FROM automation_trigger_log
					WHERE automation_id = p_automation_id
					AND contact_email = p_contact_email
				) INTO v_already_triggered;

				IF v_already_triggered THEN
					RETURN;  -- Already triggered for this contact, skip
				END IF;

				-- Record trigger for deduplication
				INSERT INTO automation_trigger_log (id, automation_id, contact_email, triggered_at)
				VALUES (gen_random_uuid()::text, p_automation_id, p_contact_email, NOW())
				ON CONFLICT (automation_id, contact_email) DO NOTHING;
			END IF;

			-- 2. Generate new ID for contact_automation
			v_new_id := gen_random_uuid()::text;

			-- 3. Enroll contact in automation
			INSERT INTO contact_automations (
				id, automation_id, contact_email, current_node_id,
				status, entered_at, scheduled_at
			) VALUES (
				v_new_id,
				p_automation_id,
				p_contact_email,
				p_root_node_id,
				'active',
				NOW(),
				NOW()
			);

			-- 4. Increment enrolled stat
			UPDATE automations
			SET stats = jsonb_set(
				COALESCE(stats, '{}'::jsonb),
				'{enrolled}',
				to_jsonb(COALESCE((stats->>'enrolled')::int, 0) + 1)
			),
			updated_at = NOW()
			WHERE id = p_automation_id;

			-- 5. Log node execution entry
			INSERT INTO automation_node_executions (
				id, contact_automation_id, automation_id, node_id, node_type, action, entered_at, output
			) VALUES (
				gen_random_uuid()::text,
				v_new_id,
				p_automation_id,
				p_root_node_id,
				'trigger',
				'entered',
				NOW(),
				'{}'::jsonb
			);

			-- 6. Create automation.start timeline event
			INSERT INTO contact_timeline (email, operation, entity_type, kind, entity_id, changes, created_at)
			VALUES (
				p_contact_email,
				'insert',
				'automation',
				'automation.start',
				p_automation_id,
				jsonb_build_object(
					'automation_id', jsonb_build_object('new', p_automation_id),
					'root_node_id', jsonb_build_object('new', p_root_node_id)
				),
				NOW()
			);

		END;
		$$ LANGUAGE plpgsql`
}
